import {getSupabase} from "./supabase.js";
const db=await getSupabase(),root=document.querySelector("#briefing");let user;
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));
const fmt=n=>Number(n||0).toLocaleString(),money=n=>"$"+(Number(n||0)/100).toFixed(2),hours=n=>(Number(n||0)/3600).toFixed(1),pct=n=>(Number(n||0)*100).toFixed(1)+"%";
function dayBounds(offset=1){const d=new Date();d.setHours(0,0,0,0);const end=new Date(d);end.setDate(end.getDate()-offset);const start=new Date(end);start.setDate(start.getDate()-1);return {start,end}}
async function build(podcastId="all",offset=1){
 const {start,end}=dayBounds(offset),ids=cache.ids;
 const E=cache.eps.filter(e=>podcastId==="all"||e.podcast_id===podcastId),eids=new Set(E.map(e=>e.id));
 const L=cache.listens.filter(x=>eids.has(x.episode_id)&&new Date(x.started_at)>=start&&new Date(x.started_at)<end);
 const F=cache.follows.filter(x=>(podcastId==="all"||x.podcast_id===podcastId)&&new Date(x.created_at)>=start&&new Date(x.created_at)<end);
 const S=cache.subs.filter(x=>(podcastId==="all"||x.podcast_id===podcastId)&&new Date(x.started_at||x.created_at)>=start&&new Date(x.started_at||x.created_at)<end);
 const R=cache.rev.filter(x=>(podcastId==="all"||x.podcast_id===podcastId)&&new Date(x.occurred_at)>=start&&new Date(x.occurred_at)<end);
 const N=cache.notes.filter(x=>new Date(x.created_at)>=start&&new Date(x.created_at)<end);
 const seconds=L.reduce((a,x)=>a+Number(x.seconds_listened||0),0),audience=new Set(L.filter(x=>x.user_id).map(x=>x.user_id)).size,completion=L.length?L.filter(x=>x.completed).length/L.length:0;
 const active=S.filter(x=>x.status==="active").length,milestones=N.filter(x=>x.notification_type==="milestone").length,attention=N.filter(x=>["distribution","publishing","revenue"].includes(x.notification_type)).length;
 const byEp={};L.forEach(x=>byEp[x.episode_id]=(byEp[x.episode_id]||0)+1);const topId=Object.keys(byEp).sort((a,b)=>byEp[b]-byEp[a])[0],top=E.find(e=>e.id===topId),revenue=R.reduce((a,x)=>a+Number(x.creator_amount||0),0);
 const summary=fmt(audience)+" identified listeners, "+fmt(L.length)+" listening sessions and "+hours(seconds)+" listening hours. "+(top?"Top episode: "+top.title+" ("+fmt(byEp[topId])+" sessions).":"No top episode recorded.")+" "+fmt(F.length)+" followers and "+fmt(S.length)+" subscription starts were recorded.";
 return {start,E,L,F,S,R,N,audience,seconds,completion,active,milestones,attention,topId,top,topSessions:topId?byEp[topId]:0,revenue,summary};
}
let cache={};
async function load(){
 if(!db){root.innerHTML='<div class="panel empty">Supabase is not configured.</div>';return}
 const a=await db.auth.getUser();user=a.data.user;if(!user){root.innerHTML='<div class="panel empty"><h2>Sign in to view your daily briefing.</h2><a class="btn primary" href="account.html">Open account</a></div>';return}
 const own=await db.from("podcast_creators").select("podcast_id").eq("user_id",user.id).eq("can_manage",true);if(own.error)throw own.error;const ids=(own.data||[]).map(x=>x.podcast_id);if(!ids.length){root.innerHTML='<div class="panel empty"><h2>No managed podcasts yet.</h2></div>';return}
 const [p,e,l,f,s,r,n]=await Promise.all([db.from("podcasts").select("id,title").in("id",ids).order("title"),db.from("podcast_episodes").select("id,podcast_id,title,play_count").in("podcast_id",ids),db.from("podcast_listens").select("id,user_id,episode_id,started_at,seconds_listened,completed").order("started_at"),db.from("podcast_follows").select("id,podcast_id,created_at").in("podcast_id",ids),db.from("podcast_subscriptions").select("id,podcast_id,status,started_at,created_at").in("podcast_id",ids),db.from("cr_creator_revenue_transactions").select("creator_amount,occurred_at,podcast_id,status").eq("user_id",user.id).in("podcast_id",ids),db.from("podcast_creator_notifications").select("id,notification_type,title,message,created_at").eq("user_id",user.id).order("created_at",{ascending:false}).limit(100)]);if(e.error)throw e.error;const eids=new Set((e.data||[]).map(x=>x.id));cache={ids,pods:p.data||[],eps:e.data||[],listens:(l.data||[]).filter(x=>eids.has(x.episode_id)),follows:f.data||[],subs:s.data||[],rev:r.data||[],notes:n.data||[]};render("all",1)}
async function render(pid,offset){const x=await build(pid,offset),date=x.start.toLocaleDateString(undefined,{weekday:"long",month:"long",day:"numeric",year:"numeric"});root.innerHTML='<div class="brief-toolbar"><select id="bPod"><option value="all">All Podcasts</option>'+cache.pods.map(p=>'<option value="'+p.id+'" '+(pid===p.id?"selected":"")+'>'+esc(p.title)+'</option>').join("")+'</select><select id="bDay"><option value="1" '+(offset===1?"selected":"")+'>Yesterday</option><option value="2" '+(offset===2?"selected":"")+'>2 days ago</option><option value="7" '+(offset===7?"selected":"")+'>7 days ago</option></select><button class="btn" id="save">Save briefing</button><a class="btn" href="growth.html">Growth Engine</a></div><article class="panel briefing-hero"><p class="eyebrow">DAILY CREATOR BRIEFING</p><h2>Yesterday on your podcast</h2><p class="muted">'+date+'</p><div class="brief-summary">'+esc(x.summary)+'</div></article><section class="brief-grid"><div class="panel"><span class="muted">Audience</span><strong>'+fmt(x.audience)+'</strong></div><div class="panel"><span class="muted">Listening</span><strong>'+hours(x.seconds)+' hrs</strong></div><div class="panel"><span class="muted">Followers</span><strong>+'+fmt(x.F.length)+'</strong></div><div class="panel"><span class="muted">Subscribers</span><strong>+'+fmt(x.S.length)+'</strong></div><div class="panel"><span class="muted">Completion</span><strong>'+pct(x.completion)+'</strong></div><div class="panel"><span class="muted">Creator revenue</span><strong>'+money(x.revenue)+'</strong></div></section><section class="brief-grid"><article class="panel"><p class="eyebrow">TOP EPISODE</p><h2>'+(x.top?esc(x.top.title):"No episode activity")+'</h2><p>'+fmt(x.topSessions)+' sessions yesterday.</p></article><article class="panel"><p class="eyebrow">MILESTONES</p><h2>'+fmt(x.milestones)+'</h2><p>Milestone alerts generated yesterday.</p></article><article class="panel"><p class="eyebrow">ATTENTION</p><h2>'+fmt(x.attention)+'</h2><p>Publishing, distribution or revenue alerts recorded.</p></article></section><section class="panel" style="margin-top:18px"><p class="eyebrow">CREATOR NOTE</p><h2>What changed</h2><p>'+esc(x.summary)+'</p><p class="muted">The briefing uses stored activity only. Missing activity is reported as zero rather than estimated.</p></section>';
 document.getElementById("bPod").onchange=e=>render(e.target.value,Number(document.getElementById("bDay").value));document.getElementById("bDay").onchange=e=>render(document.getElementById("bPod").value,Number(e.target.value));document.getElementById("save").onclick=async()=>{const row={user_id:user.id,report_date:x.start.toISOString().slice(0,10),podcast_id:pid==="all"?null:pid,audience_count:x.audience,sessions_count:x.L.length,listening_seconds:x.seconds,followers_gained:x.F.length,subscribers_started:x.S.length,active_subscribers:x.active,revenue_cents:x.revenue,top_episode_id:x.topId||null,top_episode_sessions:x.topSessions,completion_rate:x.completion,milestone_count:x.milestones,attention_count:x.attention,summary:x.summary,details:{generated_at:new Date().toISOString()}};const q=await db.from("podcast_creator_daily_briefings").upsert(row,{onConflict:"user_id,report_date,podcast_id"});if(q.error){alert(q.error.message);return}alert("Briefing saved.");};
}
load().catch(e=>{console.error(e);root.innerHTML='<div class="panel empty"><h2>Daily briefing could not load.</h2><p>'+esc(e.message||e)+'</p></div>'});