window.CROW_CONFIG={
  supabaseUrl:"https://cevylpnoexugwgygvtgu.supabase.co",
  supabaseKey:"sb_publishable_AdfM5y6RqvF3tbvEVzDZSg_JuGTQLD-",
  siteUrl:"https://crowrulesentertainment-oss.github.io/podcasting/",
  stripePublishableKey:"",
  stripeContext:"acct_1UDu0CAJsZjQLrFQ",
  stripeLivemode:true,
  stripeFunctionsBase:"/functions/v1/"
};