(()=>{"use strict";const U="https://cevylpnoexugwgygvtgu.supabase.co",K="sb_publishable_AdfM5y6RqvF3tbvEVzDZSg_JuGTQLD-",db=supabase.createClient(U,K,{auth:{persistSession:true,autoRefreshToken:true}}),$=id=>document.getElementById(id);let shows=[],selectedShow="";
const esc=s=>String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
async function call(fn,body){const {data:{session}}=await db.auth.getSession();if(!session)throw Error("Sign in required.");const r=await fetch(U+"/functions/v1/"+fn,{method:"POST",headers:{Authorization:"Bearer "+session.access_token,apikey:K,"content-type":"application/json"},body:JSON.stringify(body)});const j=await r.json().catch(()=>({}));if(!r.ok||j.error)throw Error(j.error||"Request failed.");return j}
async function boot(){try{const {data:{user}}=await db.auth.getUser();if(!user)return;const c=await db.from("creators").select("id").limit(1).maybeSingle();if(c.error||!c.data)return;const r=await db.from("podcasts").select("id,title").eq("creator_id",c.data.id).order("title");if(r.error)throw r.error;shows=r.data||[];renderShows();if(shows.length)await selectShow(shows[0].id);await refreshStripe()}catch(e){if($("stripeNotice"))$("stripeNotice").textContent=e.message}}
function renderShows(){$("stripeShow").innerHTML=shows.map(s=>'<option value="'+esc(s.id)+'">'+esc(s.title)+"</option>").join("");$("stripeShow").onchange=()=>selectShow($("stripeShow").value)}
async function refreshStripe(){try{const r=await call("podcasting-stripe-connect",{action:"status"});if(!r.connected){$("stripeStatus").textContent="NOT CONNECTED";$("stripeStatus").className="stripeStatus warn";$("stripeConnect").textContent="CONNECT STRIPE"}else{$("stripeStatus").textContent=r.capability_status==="active"||r.charges_enabled&&r.payouts_enabled?"CONNECTED · PAYMENTS READY":r.details_submitted?"CONNECTED · VERIFICATION NEEDED":"CONNECTED · FINISH ONBOARDING";$("stripeStatus").className="stripeStatus "+(r.charges_enabled&&r.payouts_enabled?"ok":"warn");$("stripeConnect").textContent=r.charges_enabled&&r.payouts_enabled?"MANAGE STRIPE":"CONTINUE STRIPE ONBOARDING"}$("stripeConnect").onclick=async()=>{try{$("stripeConnect").disabled=true;const x=await call("podcasting-stripe-connect",{action:"connect"});if(x.url)location.href=x.url;else throw Error("Stripe did not return an onboarding link.")}catch(e){$("stripeConnect").disabled=false;$("stripeNotice").textContent=e.message}}}catch(e){$("stripeStatus").textContent="UNAVAILABLE";$("stripeStatus").className="stripeStatus warn";$("stripeNotice").textContent=e.message}}
async function selectShow(id){selectedShow=id;$("stripeShow").value=id;try{const r=await call("podcasting-stripe-plan-v2",{action:"list",podcast_id:id,show_id:id});const plans=r.plans||[];renderPlans(plans);const s=await db.from("podcast_subscriptions").select("status").eq("podcast_id",id);const data=s.data||[];const active=data.filter(x=>["active","trialing"].includes(x.status)).length;$("subscriberCount").textContent=active;$("subscriberDetail").textContent=data.length+" total subscription records"}catch(e){$("planList").innerHTML='<p class="stripeError">'+esc(e.message)+"</p>"}}
function renderPlans(plans){$("planList").innerHTML=plans.length?plans.map(p=>'<div class="planRow '+(p.active?"":"inactive")+'"><div><b>'+esc(p.name)+'</b><small>$'+(Number(p.amount_cents||p.price_cents||0)/100).toFixed(2)+' · '+esc(p.interval||"month")+' · '+(p.active?"ACTIVE":"ARCHIVED")+'</small><span>'+esc(p.description||"")+'</span></div><button data-archive="'+esc(p.id)+'" '+(p.active?"":"disabled")+">"+(p.active?"ARCHIVE":"ARCHIVED")+"</button></div>").join(""):'<p>No subscriber plans yet. Create your first plan.</p>';document.querySelectorAll("[data-archive]").forEach(b=>b.onclick=async()=>{if(!confirm("Archive this plan?"))return;try{await call("podcasting-stripe-plan-v2",{action:"archive",podcast_id:selectedShow,show_id:selectedShow,plan_id:b.dataset.archive});await selectShow(selectedShow)}catch(e){alert(e.message)}})}
$("newPlan").onclick=async()=>{if(!selectedShow)return alert("Create a podcast first.");const name=prompt("Plan name","Supporter");if(!name)return;const amount=prompt("Price in USD","4.99");if(!amount)return;const cents=Math.round(Number(amount)*100);if(!Number.isInteger(cents)||cents<100)return alert("Enter a valid price of at least $1.00.");const interval=prompt("Billing interval: month or year","month")==="year"?"year":"month";try{await call("podcasting-stripe-plan-v2",{action:"create",podcast_id:selectedShow,show_id:selectedShow,name,description:"Support CrowRules Podcasting and get subscriber-only benefits.",amount_cents:cents,interval});await selectShow(selectedShow)}catch(e){alert(e.message)}};
boot();
})();