(()=>{"use strict";const U="https://baiqacotatszeqmjiekr.supabase.co",K="sb_publishable_d1HCg_kU7AtjvlTtcsfxnA_NM75pell",db=supabase.createClient(U,K,{auth:{persistSession:true,autoRefreshToken:true}}),$=id=>document.getElementById(id);let user,shows=[],plans=[],selectedShow="";
const esc=s=>String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const money=(c,i)=>new Intl.NumberFormat([],{style:"currency",currency:"USD"}).format(Number(c)/100)+(i==="year"?"/yr":"/mo");
async function call(fn,body){const {data:{session}}=await db.auth.getSession();if(!session)throw Error("Sign in required.");const r=await fetch(U+"/functions/v1/"+fn,{method:"POST",headers:{Authorization:"Bearer "+session.access_token,"apikey":K,"content-type":"application/json"},body:JSON.stringify(body)});const j=await r.json().catch(()=>({}));if(!r.ok||j.error)throw Error(j.error||"Request failed.");return j}
async function boot(){const {data:{user:u}}=await db.auth.getUser();user=u;if(!user)return;const {data:p}=await db.from("podcasting_profiles").select("account_type,is_creator").eq("id",user.id).maybeSingle();if(p?.account_type!=="podcaster"||!p?.is_creator)return;const s=await db.from("podcasting_shows").select("id,title").eq("creator_id",user.id).order("title");shows=s.data||[];renderShows();if(shows.length)await selectShow(shows[0].id);refreshStripe()}
async function refreshStripe(){try{const r=await call("podcasting-stripe-connect",{action:"status"});$("stripeStatus").textContent=r.connected?(r.charges_enabled?"CONNECTED · PAYMENTS READY":"CONNECTED · VERIFICATION NEEDED"):"NOT CONNECTED";$("stripeStatus").className="stripeStatus "+(r.charges_enabled?"ok":"warn");$("stripeConnect").textContent=r.connected?"CONTINUE STRIPE ONBOARDING":"CONNECT STRIPE";$("stripeConnect").onclick=async()=>{const x=await call("podcasting-stripe-connect",{action:"connect"});location.href=x.url}}catch(e){ $("stripeStatus").textContent=e.message;$("stripeStatus").className="stripeStatus warn"}}
function renderShows(){$("stripeShow").innerHTML=shows.map(s=>'<option value="'+s.id+'">'+esc(s.title)+"</option>").join("");$("stripeShow").onchange=()=>selectShow($("stripeShow").value)}
async function selectShow(id){selectedShow=id;$("stripeShow").value=id;try{const r=await call("podcasting-stripe-plan-v2",{action:"list",show_id:id});plans=r.plans||[];renderPlans();renderSubscribers()}catch(e){$("planList").innerHTML='<p class="stripeError">'+esc(e.message)+"</p>"}}
function renderPlans(){$("planList").innerHTML=plans.length?plans.map(p=>'<div class="planRow '+(p.active?"":"inactive")+'"><div><b>'+esc(p.name)+"</b><small>"+money(p.amount_cents,p.interval)+" · "+(p.active?"ACTIVE":"ARCHIVED")+"</small><span>"+esc(p.description||"")+'</span></div><button data-archive="'+p.id+'" '+(p.active?"":"disabled")+">"+(p.active?"ARCHIVE":"ARCHIVED")+"</button></div>").join(""):'<p>No subscriber plans yet. Create your first plan.</p>';document.querySelectorAll("[data-archive]").forEach(b=>b.onclick=async()=>{if(!confirm("Archive this plan? Existing subscribers keep their current subscription."))return;try{await call("podcasting-stripe-plan-v2",{action:"archive",show_id:selectedShow,plan_id:b.dataset.archive});await selectShow(selectedShow)}catch(e){alert(e.message)}})}
async function renderSubscribers(){const {data,error}=await db.from("podcasting_subscriptions").select("status").eq("show_id",selectedShow);if(error){$("subscriberCount").textContent="—";return}const active=(data||[]).filter(x=>["active","trialing"].includes(x.status)).length;$("subscriberCount").textContent=active;$("subscriberDetail").textContent=(data||[]).length+" total subscription records"}
$("newPlan").onclick=async()=>{const name=prompt("Plan name (example: Supporter)");if(!name)return;const amount=prompt("Monthly or annual price in USD (example: 4.99)");if(!amount)return;const interval=prompt("Billing interval: month or year","month");const cents=Math.round(Number(amount)*100);if(!Number.isInteger(cents)||cents<100)return alert("Enter a valid price of at least $1.00.");const description=prompt("Plan description (optional)","Support CrowRules Podcasting and get subscriber-only benefits.")||"";try{await call("podcasting-stripe-plan-v2",{action:"create",show_id:selectedShow,name,description,amount_cents:cents,interval:interval==="year"?"year":"month"});await selectShow(selectedShow)}catch(e){alert(e.message)}};
boot().catch(e=>{const n=$("stripeNotice");if(n)n.textContent=e.message});
})();