(()=>{
  if(window.__crowRulesInviteLoaded)return;
  window.__crowRulesInviteLoaded=true;
  const signup=new URL('signup.html?invite=podcasting',location.href).href;
  const css=`#crInviteFab{position:fixed;right:18px;bottom:18px;z-index:50000;border:1px solid rgba(0,229,255,.38);border-radius:14px;background:linear-gradient(135deg,#08101b,#18102d);color:#fff;padding:11px 15px;font:800 11px Montserrat,Arial,sans-serif;box-shadow:0 12px 35px rgba(0,0,0,.45);cursor:pointer;transition:.18s}#crInviteFab:hover{border-color:#00e5ff;transform:translateY(-2px);box-shadow:0 16px 42px rgba(0,229,255,.14)}#crInviteOverlay{position:fixed;inset:0;z-index:50001;display:none;align-items:center;justify-content:center;padding:18px;background:rgba(0,0,0,.78);backdrop-filter:blur(10px)}#crInviteOverlay.open{display:flex}.crInviteBox{width:min(560px,100%);padding:25px;border:1px solid rgba(0,229,255,.28);border-radius:22px;background:#080812;color:#fff;box-shadow:0 30px 90px rgba(0,0,0,.68)}.crInviteKicker{font:800 10px Orbitron,Arial,sans-serif;color:#00e5ff;letter-spacing:.16em}.crInviteBox h2{margin:8px 0;color:#fff;font:800 25px Montserrat,Arial,sans-serif}.crInviteBox p{color:#9da5bd;line-height:1.6;font:500 13px Montserrat,Arial,sans-serif}.crInviteLink{display:flex;gap:8px;margin:18px 0}.crInviteLink input{flex:1;min-width:0;padding:12px;border:1px solid #303540;border-radius:10px;background:#030308;color:#fff;font:600 12px Montserrat,Arial,sans-serif}.crInviteActions{display:flex;gap:8px;flex-wrap:wrap}.crInviteActions button{border:1px solid #343946;border-radius:10px;background:#181b24;color:#fff;padding:11px 14px;font:800 11px Montserrat,Arial,sans-serif;cursor:pointer}.crInviteActions .primary{background:#1877f2;border-color:#1877f2}.crInviteStatus{min-height:20px;margin-bottom:0!important}@media(max-width:600px){#crInviteFab{right:12px;bottom:12px}.crInviteLink{flex-direction:column}.crInviteBox{padding:20px}}@media(prefers-reduced-motion:reduce){#crInviteFab{transition:none}}`;
  const style=document.createElement('style');style.id='crInviteStyles';style.textContent=css;document.head.appendChild(style);
  const fab=document.createElement('button');fab.id='crInviteFab';fab.type='button';fab.setAttribute('aria-label','Invite friends to CrowRules Podcasting');fab.textContent='Invite Friends';document.body.appendChild(fab);
  const overlay=document.createElement('div');overlay.id='crInviteOverlay';overlay.innerHTML='<div class="crInviteBox" role="dialog" aria-modal="true" aria-labelledby="crInviteTitle"><div class="crInviteKicker">CROWRULES PODCASTING · INVITE</div><h2 id="crInviteTitle">Bring your friends into the CrowRules universe.</h2><p>Share CrowRules Podcasting with friends and invite them to join the community, discover shows, and create their own account.</p><div class="crInviteLink"><input id="crInviteUrl" readonly aria-label="CrowRules Podcasting invite link"></div><div class="crInviteActions"><button class="primary" type="button" id="crInviteCopy">Copy Invite Link</button><button type="button" id="crInviteShare">Share</button><button type="button" id="crInviteClose">Close</button></div><p class="crInviteStatus" id="crInviteStatus" aria-live="polite"></p></div>';
  document.body.appendChild(overlay);document.getElementById('crInviteUrl').value=signup;
  const close=()=>overlay.classList.remove('open');const status=t=>{document.getElementById('crInviteStatus').textContent=t};
  const copy=async()=>{const input=document.getElementById('crInviteUrl');try{await navigator.clipboard.writeText(input.value);status('Invite link copied — send it to your friends!')}catch(e){input.focus();input.select();document.execCommand('copy');status('Invite link copied.')}};
  fab.addEventListener('click',()=>{overlay.classList.add('open');document.getElementById('crInviteUrl').select()});document.getElementById('crInviteClose').addEventListener('click',close);document.getElementById('crInviteCopy').addEventListener('click',copy);document.getElementById('crInviteShare').addEventListener('click',async()=>{if(navigator.share){try{await navigator.share({title:'Join CrowRules Podcasting',text:'Join me on CrowRules Podcasting — The Voice of the Crow.',url:signup})}catch(e){}}else await copy()});overlay.addEventListener('click',e=>{if(e.target===overlay)close()});document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});
})();