import {getSupabase} from "./supabase.js";
const db=await getSupabase(),el=document.querySelector("#identityPage");
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));
const user=async()=>{if(!db)return null;const {data}=await db.auth.getUser();return data?.user||null};
async function load(){if(!db){el.innerHTML='<div class="panel empty">Supabase is not configured.</div>';return}const u=await user();if(!u){el.innerHTML='<div class="panel empty"><h2>Sign in first.</h2><a class="btn primary" href="account.html">Open account</a></div>';return}
const {data,error}=await db.from("podcasts").select("id,title,slug,description,category,status,author_name,author_email,language,copyright,subcategory,explicit_content,trailer_url,website_url,social_links").eq("status","published");if(error){el.innerHTML='<div class="panel empty">'+esc(error.message)+'</div>';return}
if(!data?.length){el.innerHTML='<div class="panel empty"><h2>No published podcasts yet.</h2><p>Create and publish a podcast first.</p><a class="btn primary" href="create-podcast.html">Create podcast</a></div>';return}
el.innerHTML=data.map(p=>`<form class="panel identity-form" data-id="${esc(p.id)}"><div class="section-head"><div><p class="eyebrow">PUBLISHED PODCAST</p><h2>${esc(p.title)}</h2><p class="muted">/${esc(p.slug)}</p></div><span class="status-pill published">LIVE</span></div>
<div class="form-grid"><label>Author / Host<input name="author_name" value="${esc(p.author_name||"")}"></label><label>Public contact email<input type="email" name="author_email" value="${esc(p.author_email||"")}"></label><label>Language<input name="language" value="${esc(p.language||"en-us")}" placeholder="en-us"></label><label>Copyright<input name="copyright" value="${esc(p.copyright||"")}"></label><label>Primary category<input name="category" value="${esc(p.category||"")}"></label><label>Subcategory<input name="subcategory" value="${esc(p.subcategory||"")}"></label><label>Website URL<input type="url" name="website_url" value="${esc(p.website_url||"")}" placeholder="https://"></label><label>Trailer URL<input type="url" name="trailer_url" value="${esc(p.trailer_url||"")}" placeholder="https://"></label></div>
<label class="check"><input type="checkbox" name="explicit_content" ${p.explicit_content?"checked":""}> This podcast contains explicit content</label>
<label>Social links <textarea name="social_links" rows="4" placeholder='{"youtube":"https://...","facebook":"https://..."}'>${esc(JSON.stringify(p.social_links||{},null,2))}</textarea><small class="muted">Enter a JSON object of public social profile URLs.</small></label>
<div class="actions"><button class="btn primary" type="submit">Save identity</button><a class="btn" href="distribution.html">View RSS</a></div></form>`).join("");
document.querySelectorAll("[data-id]").forEach(form=>form.addEventListener("submit",async e=>{e.preventDefault();const fd=new FormData(form);let socials={};try{socials=JSON.parse(String(fd.get("social_links")||"{}"));if(!socials||Array.isArray(socials)||typeof socials!=="object")throw Error("Social links must be a JSON object")}catch(err){alert(err.message);return}
const patch={author_name:String(fd.get("author_name")||"").trim(),author_email:String(fd.get("author_email")||"").trim(),language:String(fd.get("language")||"en-us").trim(),copyright:String(fd.get("copyright")||"").trim(),category:String(fd.get("category")||"").trim(),subcategory:String(fd.get("subcategory")||"").trim(),website_url:String(fd.get("website_url")||"").trim(),trailer_url:String(fd.get("trailer_url")||"").trim(),explicit_content:fd.get("explicit_content")==="on",social_links:socials,updated_at:new Date().toISOString()};
const {error}=await db.from("podcasts").update(patch).eq("id",form.dataset.id);if(error){alert(error.message);return}alert("Podcast identity saved.");load()}))}
load();