(()=>{const sb=window.CROW_PODCASTING;if(!sb)return;const clean=v=>String(v||"").toLowerCase().trim(),key="crowrules_listener_v9";
function read(uid){try{return JSON.parse(localStorage.getItem(key+":"+uid)||"{}")}catch(_){return{}}}
function write(uid,s){try{localStorage.setItem(key+":"+uid,JSON.stringify(s))}catch(_){}}
async function server(uid,episode,kind,seconds=0,source="player"){if(!uid||!episode)return;try{await sb.from("podcast_recommendation_events").insert({user_id:uid,episode_id:episode.id||null,podcast_id:episode.podcast_id||null,event_type:kind,seconds:Number(seconds||0),category:episode.category||null,source})}catch(_){}}
function signal(uid,episode,kind="play"){if(!uid||!episode)return;const s=read(uid),now=Date.now(),e=s[episode.id]||{plays:0,seconds:0,signals:0,last:0,first:now};e.signals++;e.last=now;if(kind==="play")e.plays++;if(kind==="complete")e.completes=(e.completes||0)+1;if(kind==="progress")e.seconds+=Math.max(0,Number(episode.seconds||0));e.category=episode.category||e.category;e.podcast_id=episode.podcast_id||e.podcast_id;s[episode.id]=e;write(uid,s);if(kind!=="progress"||Number(episode.seconds||0)>=30)server(uid,episode,kind,episode.seconds||0)}
async function serverProfile(uid){try{const{data}=await sb.from("podcast_recommendation_events").select("episode_id,podcast_id,event_type,seconds,category,created_at").eq("user_id",uid).order("created_at",{ascending:false}).limit(500);return data||[]}catch(_){return[]}}
async function profile(){const{data:{user}}=await sb.auth.getUser();if(!user)return null;const[pr,re,fo,sa,qu,events]=await Promise.all([sb.from("podcast_user_episode_progress").select("episode_id,position_seconds,duration_seconds,completed,updated_at").eq("user_id",user.id).order("updated_at",{ascending:false}).limit(100),sb.from("podcast_user_recently_played").select("episode_id,last_played_at,play_position_seconds").eq("user_id",user.id).order("last_played_at",{ascending:false}).limit(100),sb.from("podcast_user_library").select("podcast_id,item_type,created_at").eq("user_id",user.id),sb.from("podcast_user_saved_episodes").select("episode_id,created_at").eq("user_id",user.id),sb.from("podcast_user_queue").select("episode_id,position").eq("user_id",user.id).order("position"),serverProfile(user.id)]);const ids=[...new Set([...(pr.data||[]),...(re.data||[]),...(sa.data||[]),...(events||[]).map(x=>x.episode_id)].filter(Boolean))];let eps=[];if(ids.length){const{data}=await sb.from("podcast_episodes").select("id,podcast_id,title,description,audio_url,thumbnail_url,duration_seconds,play_count,published_at,podcasts(id,title,category,artwork_url)").in("id",ids);eps=data||[]}const em=new Map(eps.map(e=>[e.id,e])),followed=(fo.data||[]).filter(x=>clean(x.item_type)==="follow").map(x=>x.podcast_id),completed=(pr.data||[]).filter(x=>x.completed).map(x=>x.episode_id),signals=read(user.id),categoryScore={},showScore={};eps.forEach(e=>{const c=e.podcasts?.category;if(c)categoryScore[c]=(categoryScore[c]||0)+1;showScore[e.podcast_id]=(showScore[e.podcast_id]||0)+1});Object.values(signals).forEach(x=>{if(x.category)categoryScore[x.category]=(categoryScore[x.category]||0)+Math.min(8,(x.plays||0)+(x.completes||0)*2)});(events||[]).forEach(x=>{if(x.category)categoryScore[x.category]=(categoryScore[x.category]||0)+(.5+Number(x.seconds||0)/3600)});const topCategories=Object.entries(categoryScore).sort((a,b)=>b[1]-a[1]).map(x=>x[0]).slice(0,5);let streak=0;const days=new Set((re.data||[]).map(x=>new Date(x.last_played_at).toISOString().slice(0,10)));let d=new Date;for(;;){const k=d.toISOString().slice(0,10);if(days.has(k)){streak++;d.setDate(d.getDate()-1)}else break}return{user,progress:pr.data||[],recent:re.data||[],follows:followed,saved:(sa.data||[]).map(x=>x.episode_id),queue:qu.data||[],episodes:eps,em,completed,topCategories,showScore,streak,signals,events:events||[]}}
async function catalog(limit=150){const{data}=await sb.from("podcast_episodes").select("id,podcast_id,title,description,audio_url,thumbnail_url,duration_seconds,play_count,published_at,podcasts(id,title,category,artwork_url,creator_id)").eq("status","published").order("published_at",{ascending:false}).limit(limit);return data||[]}
function score(e,p){const cat=e.podcasts?.category||"",sig=p?.signals?.[e.id]||{},age=Math.max(0,(Date.now()-new Date(e.published_at||Date.now()).getTime())/86400000);let n=0;if(p?.follows?.includes(e.podcast_id))n+=100;if(p?.topCategories?.includes(cat))n+=55-p.topCategories.indexOf(cat)*8;n+=(sig.plays||0)*14+(sig.completes||0)*20;n+=Math.min(25,Number(e.play_count||0)/80);n+=Math.max(0,15-age);return n}
async function recommendations(p){if(!p)return[];const exclude=new Set([...p.recent.map(x=>x.episode_id),...p.saved,...p.completed]);return(await catalog()).filter(e=>e.audio_url&&!exclude.has(e.id)).map(e=>({...e,_score:score(e,p),_reason:p.follows.includes(e.podcast_id)?"Because you follow this show":p.topCategories.includes(e.podcasts?.category)?"Because you listen to "+e.podcasts.category:"Popular with listeners"})).sort((a,b)=>b._score-a._score).slice(0,18)}
async function moreLikeThis(p,id){if(!p||!id)return[];const base=p.em?.get(id);if(!base)return[];const exclude=new Set([...p.recent.map(x=>x.episode_id),...p.saved,...p.completed]);return(await catalog()).filter(e=>e.audio_url&&e.id!==id&&!exclude.has(e.id)).map(e=>{let n=0;if(e.podcast_id===base.podcast_id)n+=120;if(e.podcasts?.category===base.podcasts?.category)n+=65;n+=Math.min(20,Number(e.play_count||0)/100);return{...e,_score:n}}).sort((a,b)=>b._score-a._score).slice(0,12)}
function personalizedGenres(p){const out={};Object.values(p?.signals||{}).forEach(x=>{if(x.category)out[x.category]=(out[x.category]||0)+(x.plays||0)*3+(x.completes||0)*5+(x.seconds||0)/3600});(p?.events||[]).forEach(x=>{if(x.category)out[x.category]=(out[x.category]||0)+.25+Number(x.seconds||0)/3600});return out}
async function trending(days=0){const all=await catalog(200),cut=days?Date.now()-days*86400000:0;return all.filter(e=>e.audio_url&&(!cut||new Date(e.published_at||0).getTime()>=cut)).map(e=>{const age=Math.max(0,(Date.now()-new Date(e.published_at||Date.now()).getTime())/86400000),plays=Number(e.play_count||0),fresh=Math.max(0,30-age*2),momentum=Math.min(70,Math.log1p(plays)*9);return{...e,_trend_score:momentum+fresh}}).sort((a,b)=>b._trend_score-a._trend_score).slice(0,18)}
async function becauseYouFollow(p){if(!p)return[];return(await catalog(200)).filter(e=>e.audio_url&&p.follows.includes(e.podcast_id)&&!p.completed.includes(e.id)).sort((a,b)=>Number(b.play_count||0)-Number(a.play_count||0)).slice(0,18)}
async function popularInYourGenres(p){if(!p)return[];const cats=p.topCategories||[];return(await catalog(200)).filter(e=>e.audio_url&&cats.includes(e.podcasts?.category)&&!p.completed.includes(e.id)).map(e=>({...e,_genre_score:(cats.length-cats.indexOf(e.podcasts?.category))*20+Math.min(30,Number(e.play_count||0)/50)})).sort((a,b)=>b._genre_score-a._genre_score).slice(0,18)}
async function creatorPicks(p){if(!p)return[];const cats=p.topCategories||[],follow=p.follows||[];return(await catalog(200)).filter(e=>e.audio_url&&((follow.includes(e.podcast_id))||cats.includes(e.podcasts?.category))).map(e=>({...e,_creator_score:(follow.includes(e.podcast_id)?100:0)+(cats.includes(e.podcasts?.category)?40:0)+Math.min(20,Number(e.play_count||0)/100)})).sort((a,b)=>b._creator_score-a._creator_score).slice(0,18)}
window.CrowListener={profile,recommendations,moreLikeThis,personalizedGenres,signal,trending,becauseYouFollow,popularInYourGenres,creatorPicks,server};
})();