import {getSupabase} from "./supabase.js";
const API="https://cevylpnoexugwgygvtgu.supabase.co/functions/v1/podcast-live-public",MOD="https://cevylpnoexugwgygvtgu.supabase.co/functions/v1/podcast-live-moderation";
const qs=new URLSearchParams(location.search),slug=qs.get("room")||"";
let supabase,broadcast,room,safety,chatChannel,moderationChannel,timer,presenceId,sessionId,heartbeat;
const $=id=>document.getElementById(id),esc=s=>String(s??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;");
const uuid=()=>crypto.randomUUID(),media=b=>b?.playback_hls_url||b?.podcast_live_replays?.hls_url||b?.playback_url||b?.podcast_live_replays?.mp4_url||b?.podcast_live_replays?.media_url;
async function user(){return (await supabase.auth.getUser()).data.user}
async function engagement(type,metadata={}){const u=await user();if(u&&broadcast)await supabase.from("podcast_live_engagement_events").insert({broadcast_id:broadcast.id,user_id:u.id,session_id:sessionId,event_type:type,metadata})}
async function loadSafety(){if(!broadcast)return;const q=await supabase.from("podcast_live_safety_state").select("*").eq("podcast_id",broadcast.podcast_id).maybeSingle();safety=q.data||{chat_enabled:true,reactions_enabled:true,slow_mode_seconds:0};const banner=$("safetyBanner");let msg="";if(!safety.chat_enabled)msg="Live chat is currently paused by the creator.";else if(safety.slow_mode_seconds)msg="Slow mode is active: one message every "+safety.slow_mode_seconds+" seconds.";if(safety.audience_alert&&(!safety.audience_alert_expires_at||new Date(safety.audience_alert_expires_at)>new Date()))msg=safety.audience_alert;if(msg){banner.hidden=false;banner.innerHTML="<strong>LIVE SAFETY</strong><div>"+esc(msg)+"</div>"}else banner.hidden=true;$("chatInput").disabled=!safety.chat_enabled;$("reactBtn").disabled=!safety.reactions_enabled;$("chatNotice").textContent=safety.chat_enabled?"":"Chat is temporarily paused."}
async function startPresence(){if(!broadcast||broadcast.status!=="live")return;const u=await user();if(!u)return;sessionId=sessionId||uuid();const q=await supabase.from("podcast_live_presence").insert({broadcast_id:broadcast.id,user_id:u.id,session_id:sessionId}).select("id").single();if(!q.error)presenceId=q.data.id;await engagement("join");heartbeat=setInterval(()=>presenceId&&supabase.from("podcast_live_presence").update({last_seen_at:new Date().toISOString()}).eq("id",presenceId),15000)}
async function updateAudience(){if(!broadcast)return;const cutoff=new Date(Date.now()-45000).toISOString();const q=await supabase.from("podcast_live_presence").select("id",{count:"exact",head:true}).eq("broadcast_id",broadcast.id).is("left_at",null).gte("last_seen_at",cutoff);$("listenerCount").textContent=(q.count||0)+" live listeners • "+(broadcast.peak_viewers||0)+" peak";const r=await supabase.from("podcast_live_reactions").select("id",{count:"exact",head:true}).eq("broadcast_id",broadcast.id);$("reactionCount").textContent=r.count||0}
async function load(){try{const r=await fetch(API+(slug?"?slug="+encodeURIComponent(slug):"")),o=await r.json();if(!r.ok)throw Error(o.error||"Live service unavailable");broadcast=o.broadcast;render();await loadSafety();await setupChat();await startPresence();await updateAudience()}catch(e){$("roomStatus").textContent="UNAVAILABLE";$("roomDescription").textContent=e.message}}
function render(){if(!broadcast){$("roomStatus").textContent="OFFLINE";$("roomTitle").textContent="No live transmission";$("roomDescription").textContent="There is no active CrowRules Podcasting broadcast right now.";return}$("roomTitle").textContent=broadcast.title||"CrowRules Live";$("roomDescription").textContent=broadcast.description||"Live CrowRules Podcasting transmission";$("roomStats").textContent=broadcast.status.toUpperCase();const u=media(broadcast);if(u&&$("roomVideo").dataset.src!==u){$("roomVideo").dataset.src=u;$("roomVideo").src=u;$("roomVideo").play().catch(()=>{})}$("roomStatus").textContent=broadcast.status==="live"?"LIVE":broadcast.status==="processing"?"PROCESSING REPLAY":"REPLAY"}
async function setupChat(){if(!supabase||!slug)return;const rr=await supabase.from("podcast_chat_rooms").select("id,slug,name").eq("slug",slug).maybeSingle();room=rr.data;if(!room){$("chatNotice").textContent="Live chat room is not provisioned for this channel.";return}const msgs=await supabase.from("podcast_chat_messages").select("id,display_name,message,created_at").eq("room_id",room.id).eq("is_hidden",false).order("created_at",{ascending:false}).limit(50);(msgs.data||[]).reverse().forEach(addMessage);chatChannel=supabase.channel("podcast-chat-"+room.id).on("postgres_changes",{event:"INSERT",schema:"public",table:"podcast_chat_messages",filter:"room_id=eq."+room.id},p=>addMessage(p.new)).subscribe();const u=await user();if(!u){$("chatInput").disabled=true;$("chatNotice").textContent="Sign in to participate in live chat."}}
function addMessage(m){const box=$("messages"),div=document.createElement("div");div.className="chat-message";div.innerHTML="<strong>"+esc(m.display_name||"Listener")+"</strong><p>"+esc(m.message)+"</p>";box.append(div);box.scrollTop=box.scrollHeight}
$("chatForm").addEventListener("submit",async e=>{e.preventDefault();const input=$("chatInput"),message=input.value.trim();if(!message||!room)return;const u=await user();if(!u){$("chatNotice").textContent="Sign in to chat.";return}const name=u.user_metadata?.full_name||u.user_metadata?.name||u.email?.split("@")[0]||"Listener";const q=await supabase.from("podcast_chat_messages").insert({room_id:room.id,user_id:u.id,display_name:name,message});if(q.error)$("chatNotice").textContent=q.error.message;else{input.value="";await engagement("chat")}})
$("reactBtn").addEventListener("click",async()=>{const u=await user();if(!u){$("chatNotice").textContent="Sign in to react.";return}const q=await supabase.from("podcast_live_reactions").insert({broadcast_id:broadcast.id,user_id:u.id,reaction:"heart"});if(q.error)$("chatNotice").textContent=q.error.message;else{await engagement("reaction");await updateAudience()}})
$("reportBtn").onclick=async()=>{const u=await user();if(!u){$("chatNotice").textContent="Sign in to submit a report.";return}const category=prompt("Report category: harassment, spam, hate, threat, sexual, impersonation, other","other");if(!category)return;const description=prompt("Brief description (optional):","");const s=(await supabase.auth.getSession()).data.session;const r=await fetch(MOD,{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+s.access_token},body:JSON.stringify({action:"report",broadcast_id:broadcast.id,category,description})});const o=await r.json();$("chatNotice").textContent=o.error||"Report submitted for moderator review."}
$("unmuteBtn").onclick=async()=>{$("roomVideo").muted=false;await engagement("play");$("roomVideo").play().catch(()=>{})}
(async()=>{supabase=await getSupabase();await load();timer=setInterval(load,5000);moderationChannel=supabase.channel("live-safety-"+(broadcast?.id||"default")).on("postgres_changes",{event:"*",schema:"public",table:"podcast_live_safety_state",filter:broadcast?"podcast_id=eq."+broadcast.podcast_id:undefined},load).on("postgres_changes",{event:"INSERT",schema:"public",table:"podcast_live_moderation_actions",filter:broadcast?"broadcast_id=eq."+broadcast.id:undefined},p=>{if(p.new?.action==="alert"&&p.new?.metadata?.message){$("safetyBanner").hidden=false;$("safetyBanner").innerHTML="<strong>LIVE ALERT</strong><div>"+esc(p.new.metadata.message)+"</div>"}}).subscribe()})()
window.addEventListener("beforeunload",()=>{clearInterval(timer);clearInterval(heartbeat);if(presenceId)supabase.from("podcast_live_presence").update({left_at:new Date().toISOString()}).eq("id",presenceId);if(chatChannel)supabase.removeChannel(chatChannel);if(moderationChannel)supabase.removeChannel(moderationChannel)})