import {getSupabase} from "./supabase.js";
const API="https://cevylpnoexugwgygvtgu.supabase.co/functions/v1/podcast-live-public";
const qs=new URLSearchParams(location.search),slug=qs.get("room")||"";
let supabase,broadcast,room,chatChannel,moderationChannel,timer,presenceId,sessionId,heartbeat;
const $=id=>document.getElementById(id);
const esc=s=>String(s??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;");
function media(b){return b?.playback_hls_url||b?.podcast_live_replays?.hls_url||b?.playback_url||b?.podcast_live_replays?.mp4_url||b?.podcast_live_replays?.media_url}
function uuid(){return crypto.randomUUID()}
async function engagement(type,metadata={}){if(!supabase||!broadcast)return;const {data:{user}}=await supabase.auth.getUser();if(user)await supabase.from("podcast_live_engagement_events").insert({broadcast_id:broadcast.id,user_id:user.id,session_id:sessionId,event_type:type,metadata})}
async function startPresence(){if(!broadcast||broadcast.status!=="live")return;const {data:{user}}=await supabase.auth.getUser();if(!user)return;sessionId=sessionId||uuid();const {data,error}=await supabase.from("podcast_live_presence").insert({broadcast_id:broadcast.id,user_id:user.id,session_id:sessionId}).select("id").single();if(!error)presenceId=data.id;await engagement("join");heartbeat=setInterval(()=>{if(presenceId)supabase.from("podcast_live_presence").update({last_seen_at:new Date().toISOString()}).eq("id",presenceId)},15000)}
async function updateAudience(){if(!broadcast)return;const cutoff=new Date(Date.now()-45000).toISOString();const {count}=await supabase.from("podcast_live_presence").select("id",{count:"exact",head:true}).eq("broadcast_id",broadcast.id).is("left_at",null).gte("last_seen_at",cutoff);$("listenerCount").textContent=(count||0)+" live listeners • "+(broadcast.peak_viewers||0)+" peak";const {count:rc}=await supabase.from("podcast_live_reactions").select("id",{count:"exact",head:true}).eq("broadcast_id",broadcast.id);$("reactionCount").textContent=rc||0}
async function load(){try{const r=await fetch(API+(slug?"?slug="+encodeURIComponent(slug):""));const o=await r.json();if(!r.ok)throw Error(o.error||"Live service unavailable");broadcast=o.broadcast;render();await setupChat();await startPresence();await updateAudience();await loadAlert()}catch(e){$("roomStatus").textContent="UNAVAILABLE";$("roomDescription").textContent=e.message}}
function render(){if(!broadcast){$("roomStatus").textContent="OFFLINE";$("roomTitle").textContent="No live transmission";$("roomDescription").textContent="There is no active CrowRules Podcasting broadcast right now.";return}$("roomTitle").textContent=broadcast.title||"CrowRules Live";$("roomDescription").textContent=broadcast.description||"Live CrowRules Podcasting transmission";$("roomStats").textContent=broadcast.status.toUpperCase();const u=media(broadcast);if(u&&$("roomVideo").dataset.src!==u){$("roomVideo").dataset.src=u;$("roomVideo").src=u;$("roomVideo").play().catch(()=>{})}if(broadcast.status==="live")$("roomStatus").textContent="LIVE";else if(broadcast.status==="processing")$("roomStatus").textContent="PROCESSING REPLAY";else $("roomStatus").textContent="REPLAY"}
async function setupChat(){if(!supabase||!slug)return;const {data:rr}=await supabase.from("podcast_chat_rooms").select("id,slug,name").eq("slug",slug).maybeSingle();room=rr;if(!room){$("chatNotice").textContent="Live chat room is not provisioned for this channel.";return}const {data:msgs}=await supabase.from("podcast_chat_messages").select("id,display_name,message,created_at").eq("room_id",room.id).eq("is_hidden",false).order("created_at",{ascending:false}).limit(50);(msgs||[]).reverse().forEach(addMessage);chatChannel=supabase.channel("podcast-chat-"+room.id).on("postgres_changes",{event:"INSERT",schema:"public",table:"podcast_chat_messages",filter:"room_id=eq."+room.id},p=>addMessage(p.new)).subscribe();const {data:{user}}=await supabase.auth.getUser();if(!user){$("chatInput").disabled=true;$("chatNotice").textContent="Sign in to participate in live chat."}}
function addMessage(m){const box=$("messages"),div=document.createElement("div");div.className="chat-message";div.innerHTML="<strong>"+esc(m.display_name||"Listener")+"</strong><p>"+esc(m.message)+"</p>";box.append(div);box.scrollTop=box.scrollHeight}
async function loadAlert(){if(!broadcast)return;const {data}=await supabase.from("podcast_live_moderation_actions").select("metadata,created_at").eq("broadcast_id",broadcast.id).eq("action","alert").order("created_at",{ascending:false}).limit(1).maybeSingle();if(data?.metadata?.message)showAlert(data.metadata.message)}
function showAlert(message){let box=$("liveAudienceAlert");if(!box){box=document.createElement("div");box.id="liveAudienceAlert";box.style.cssText="margin:12px 0;padding:12px;border:1px solid rgba(0,210,255,.35);border-radius:12px;background:rgba(0,210,255,.08)";$("messages").parentElement?.prepend(box)}box.innerHTML="<strong>LIVE ALERT</strong><div>"+esc(message)+"</div>"}
$("chatForm").addEventListener("submit",async e=>{e.preventDefault();const input=$("chatInput"),message=input.value.trim();if(!message||!room)return;const {data:{user}}=await supabase.auth.getUser();if(!user){$("chatNotice").textContent="Sign in to chat.";return}const name=user.user_metadata?.full_name||user.user_metadata?.name||user.email?.split("@")[0]||"Listener";const {error}=await supabase.from("podcast_chat_messages").insert({room_id:room.id,user_id:user.id,display_name:name,message});if(error)$("chatNotice").textContent=error.message;else{input.value="";await engagement("chat")}})
$("reactBtn").addEventListener("click",async()=>{if(!broadcast||!supabase)return;const {data:{user}}=await supabase.auth.getUser();if(!user){$("chatNotice").textContent="Sign in to react.";return}const {error}=await supabase.from("podcast_live_reactions").insert({broadcast_id:broadcast.id,user_id:user.id,reaction:"heart"});if(error){$("chatNotice").textContent=error.message}else{await engagement("reaction");await updateAudience()}})
$("unmuteBtn").onclick=async()=>{$("roomVideo").muted=false;await engagement("play");$("roomVideo").play().catch(()=>{})}
(async()=>{supabase=await getSupabase();await load();timer=setInterval(load,5000);moderationChannel=supabase.channel("live-moderation-public-"+(slug||"default")).on("postgres_changes",{event:"INSERT",schema:"public",table:"podcast_live_moderation_actions",filter:broadcast?"broadcast_id=eq."+broadcast.id:"action=eq.alert"},p=>{if(p.new?.action==="alert"&&p.new?.metadata?.message)showAlert(p.new.metadata.message)}).subscribe()})()
window.addEventListener("beforeunload",async()=>{clearInterval(timer);clearInterval(heartbeat);if(presenceId)await supabase.from("podcast_live_presence").update({left_at:new Date().toISOString()}).eq("id",presenceId);if(broadcast)await engagement("leave");if(chatChannel)supabase.removeChannel(chatChannel);if(moderationChannel)supabase.removeChannel(moderationChannel)})