/* CrowRules Podcasting — Member Action Layer */
(()=>{"use strict";
const S=()=>window.CrowRulesMemberState,login=()=>{location.href="login.html?redirect="+encodeURIComponent(location.pathname.split("/").pop()+location.search)};
function busy(b,v,t){if(!b)return;if(v){b.dataset.orig=b.textContent;b.disabled=true;b.setAttribute("aria-busy","true");if(t)b.textContent=t}else{b.disabled=false;b.removeAttribute("aria-busy");if(b.dataset.orig){b.textContent=b.dataset.orig;delete b.dataset.orig}}}
function paint(b,on,yes,no){b.setAttribute("aria-pressed",String(!!on));b.dataset.active=on?"true":"false";b.textContent=on?yes:no}
async function auth(){if(S()?.client&&S()?.userId)return true;login();return false}
async function togglePodcastFollow(b,id){if(!(await auth()))return;const s=S(),db=s.client,uid=s.userId,was=b.dataset.active==="true",next=!was;paint(b,next,"Following","Follow");busy(b,true,next?"Following…":"Unfollowing…");const r=await s.optimistic({key:"podcast-follow:"+id,label:next?"Follow podcast":"Unfollow podcast",apply:async()=>{},rollback:async()=>paint(b,was,"Following","Follow"),commit:async()=>next?db.from("podcast_follows").insert({user_id:uid,podcast_id:id}):db.from("podcast_follows").delete().eq("user_id",uid).eq("podcast_id",id),success:next?"Podcast followed":"Podcast unfollowed",failure:next?"Follow failed — restored":"Unfollow failed — restored"});busy(b,false);if(r.ok)paint(b,next,"Following","Follow");return r}
async function toggleEpisodeSave(b,id){if(!(await auth()))return;const s=S(),db=s.client,uid=s.userId,was=b.dataset.active==="true",next=!was;paint(b,next,"Saved","Save");busy(b,true,next?"Saving…":"Removing…");const r=await s.optimistic({key:"episode-save:"+id,label:next?"Save episode":"Remove saved episode",apply:async()=>{},rollback:async()=>paint(b,was,"Saved","Save"),commit:async()=>next?db.from("podcast_saved_episodes").insert({user_id:uid,episode_id:id}):db.from("podcast_saved_episodes").delete().eq("user_id",uid).eq("episode_id",id),success:next?"Episode saved":"Episode removed from saved",failure:next?"Save failed — restored":"Remove failed — restored"});busy(b,false);if(r.ok)paint(b,next,"Saved","Save");return r}
async function toggleMemberFollow(b,id){if(!(await auth()))return;const s=S(),db=s.client,uid=s.userId;if(uid===id)return;const was=b.dataset.active==="true",next=!was;paint(b,next,"Following","Follow");busy(b,true,next?"Following…":"Unfollowing…");const r=await s.optimistic({key:"member-follow:"+id,label:next?"Follow member":"Unfollow member",apply:async()=>{},rollback:async()=>paint(b,was,"Following","Follow"),commit:async()=>next?db.from("podcast_member_follows").insert({follower_user_id:uid,followed_user_id:id}):db.from("podcast_member_follows").delete().eq("follower_user_id",uid).eq("followed_user_id",id),success:next?"Member followed":"Member unfollowed",failure:next?"Follow failed — restored":"Unfollow failed — restored"});busy(b,false);if(r.ok)paint(b,next,"Following","Follow");return r}
async function markNotificationRead(b,id){if(!(await auth()))return;if(b.dataset.active==="true")return;const s=S(),db=s.client,uid=s.userId;paint(b,true,"Read","Mark read");busy(b,true,"Marking…");const r=await s.optimistic({key:"notification-read:"+id,label:"Mark notification read",apply:async()=>{},rollback:async()=>paint(b,false,"Read","Mark read"),commit:async()=>db.from("podcast_notifications").update({is_read:true}).eq("id",id).eq("user_id",uid),success:"Notification marked read",failure:"Notification update failed — restored"});busy(b,false);if(r.ok)paint(b,true,"Read","Mark read");return r}
function bind(){document.querySelectorAll("[data-follow-podcast]").forEach(b=>{if(b.dataset.crBound)return;b.dataset.crBound="1";b.addEventListener("click",()=>togglePodcastFollow(b,b.dataset.followPodcast))});document.querySelectorAll("[data-save-episode]").forEach(b=>{if(b.dataset.crBound)return;b.dataset.crBound="1";b.addEventListener("click",()=>toggleEpisodeSave(b,b.dataset.saveEpisode))});document.querySelectorAll("[data-follow-member]").forEach(b=>{if(b.dataset.crBound)return;b.dataset.crBound="1";b.addEventListener("click",()=>toggleMemberFollow(b,b.dataset.followMember))});document.querySelectorAll("[data-notification-read]").forEach(b=>{if(b.dataset.crBound)return;b.dataset.crBound="1";b.addEventListener("click",()=>markNotificationRead(b,b.dataset.notificationRead))})}
async function hydrate(){if(!S()?.client||!S()?.userId)return;const s=S(),db=s.client,uid=s.userId;const pids=[...document.querySelectorAll("[data-follow-podcast]")].map(b=>b.dataset.followPodcast).filter(Boolean),eids=[...document.querySelectorAll("[data-save-episode]")].map(b=>b.dataset.saveEpisode).filter(Boolean),mids=[...document.querySelectorAll("[data-follow-member]")].map(b=>b.dataset.followMember).filter(Boolean);const [p,e,m]=await Promise.all([pids.length?db.from("podcast_follows").select("podcast_id").eq("user_id",uid).in("podcast_id",pids):{data:[]},eids.length?db.from("podcast_saved_episodes").select("episode_id").eq("user_id",uid).in("episode_id",eids):{data:[]},mids.length?db.from("podcast_member_follows").select("followed_user_id").eq("follower_user_id",uid).in("followed_user_id",mids):{data:[]}]);const ps=new Set((p.data||[]).map(x=>String(x.podcast_id))),es=new Set((e.data||[]).map(x=>String(x.episode_id))),ms=new Set((m.data||[]).map(x=>String(x.followed_user_id)));document.querySelectorAll("[data-follow-podcast]").forEach(b=>paint(b,ps.has(String(b.dataset.followPodcast)),"Following","Follow"));document.querySelectorAll("[data-save-episode]").forEach(b=>paint(b,es.has(String(b.dataset.saveEpisode)),"Saved","Save"));document.querySelectorAll("[data-follow-member]").forEach(b=>paint(b,ms.has(String(b.dataset.followMember)),"Following","Follow"))}
window.CrowRulesMemberActions={togglePodcastFollow,toggleEpisodeSave,toggleMemberFollow,markNotificationRead,bind,hydrate};const boot=()=>{bind();setTimeout(hydrate,300)};if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else boot();window.addEventListener("crowrules:member-state",e=>{if(e.detail?.reason==="ready")hydrate()});
})();