/* CrowRules Podcasting — Member Actions 2.0 */
(()=>{"use strict";
const S=()=>window.CrowRulesMemberState;
const login=()=>{location.href="login.html?redirect="+encodeURIComponent(location.pathname.split("/").pop()+location.search)};
function paint(b,on,yes,no){if(!b)return;b.setAttribute("aria-pressed",String(!!on));b.dataset.active=on?"true":"false";b.textContent=on?yes:no}
function busy(b,v,t){if(!b)return;if(v){b.dataset.orig=b.textContent;b.disabled=true;b.setAttribute("aria-busy","true");if(t)b.textContent=t}else{b.disabled=false;b.removeAttribute("aria-busy");if(b.dataset.orig){b.textContent=b.dataset.orig;delete b.dataset.orig}}}
async function auth(){if(S()?.client&&S()?.userId)return true;login();return false}
async function act(b,key,label,commit,on,off){if(!(await auth()))return;const s=S(),was=b.dataset.active==="true",next=!was;paint(b,next,on,off);busy(b,true,next?on+"…":off+"…");const r=await s.optimistic({key,label,apply:async()=>{},rollback:async()=>paint(b,was,on,off),commit,success:next?label+" complete":label+" removed",failure:label+" failed — restored"});busy(b,false);if(r.ok)paint(b,next,on,off);return r}
async function togglePodcastFollow(b,id){return act(b,"podcast-follow:"+id,"Podcast follow",()=>b.dataset.active==="true"?S().client.rpc("unfollow_my_podcast",{p_podcast_id:id}):S().client.rpc("follow_my_podcast",{p_podcast_id:id}),"Following","Follow")}
async function toggleEpisodeSave(b,id){return act(b,"episode-save:"+id,"Episode save",()=>b.dataset.active==="true"?S().client.rpc("remove_my_podcast_item",{p_item_type:"episode",p_item_id:id}):S().client.rpc("save_my_podcast_item",{p_item_type:"episode",p_item_id:id}),"Saved","Save")}
async function toggleEpisodeFavorite(b,id){return act(b,"episode-favorite:"+id,"Episode favorite",()=>b.dataset.active==="true"?S().client.rpc("remove_my_podcast_item",{p_item_type:"favorite",p_item_id:id}):S().client.rpc("save_my_podcast_item",{p_item_type:"favorite",p_item_id:id}),"Favorited","Favorite")}
async function toggleMemberFollow(b,id){if(!(await auth()))return;const s=S(),uid=s.userId;if(uid===id)return;const was=b.dataset.active==="true",next=!was;paint(b,next,"Following","Follow");busy(b,true,next?"Following…":"Unfollowing…");const r=await s.optimistic({key:"member-follow:"+id,label:"Member follow",apply:async()=>{},rollback:async()=>paint(b,was,"Following","Follow"),commit:async()=>next?s.client.from("podcast_member_follows").insert({follower_user_id:uid,followed_user_id:id}):s.client.from("podcast_member_follows").delete().eq("follower_user_id",uid).eq("followed_user_id",id)});busy(b,false);if(r.ok)paint(b,next,"Following","Follow");return r}
async function markNotificationRead(b,id){if(!(await auth()))return;if(b.dataset.active==="true")return;const s=S(),uid=s.userId;return act(b,"notification-read:"+id,"Notification read",()=>s.client.from("podcast_notifications").update({is_read:true}).eq("id",id).eq("user_id",uid),"Read","Mark read")}
function bind(){document.querySelectorAll("[data-follow-podcast]").forEach(b=>{if(b.dataset.crBound)return;b.dataset.crBound="1";b.addEventListener("click",()=>togglePodcastFollow(b,b.dataset.followPodcast))});document.querySelectorAll("[data-save-episode]").forEach(b=>{if(b.dataset.crBound)return;b.dataset.crBound="1";b.addEventListener("click",()=>toggleEpisodeSave(b,b.dataset.saveEpisode))});document.querySelectorAll("[data-favorite-episode]").forEach(b=>{if(b.dataset.crBound)return;b.dataset.crBound="1";b.addEventListener("click",()=>toggleEpisodeFavorite(b,b.dataset.favoriteEpisode))});document.querySelectorAll("[data-follow-member]").forEach(b=>{if(b.dataset.crBound)return;b.dataset.crBound="1";b.addEventListener("click",()=>toggleMemberFollow(b,b.dataset.followMember))});document.querySelectorAll("[data-notification-read]").forEach(b=>{if(b.dataset.crBound)return;b.dataset.crBound="1";b.addEventListener("click",()=>markNotificationRead(b,b.dataset.notificationRead))})}
async function hydrate(){if(!S()?.client||!S()?.userId)return;const s=S(),db=s.client;const pids=[...document.querySelectorAll("[data-follow-podcast]")].map(b=>b.dataset.followPodcast).filter(Boolean);const eids=[...document.querySelectorAll("[data-save-episode],[data-favorite-episode]")].map(b=>b.dataset.saveEpisode||b.dataset.favoriteEpisode).filter(Boolean);const mids=[...document.querySelectorAll("[data-follow-member]")].map(b=>b.dataset.followMember).filter(Boolean);const [lib,following,members]=await Promise.all([db.rpc("get_my_podcast_library"),db.rpc("get_my_podcast_following"),mids.length?db.from("podcast_member_follows").select("followed_user_id").eq("follower_user_id",s.userId).in("followed_user_id",mids):{data:[]}]);const rows=lib.data||[],ps=new Set((following.data||[]).map(x=>String(x.podcast_id))),es=new Set(rows.filter(x=>x.item_type==="episode").map(x=>String(x.episode_id))),fs=new Set(rows.filter(x=>x.item_type==="favorite").map(x=>String(x.episode_id))),ms=new Set((members.data||[]).map(x=>String(x.followed_user_id)));document.querySelectorAll("[data-follow-podcast]").forEach(b=>paint(b,ps.has(String(b.dataset.followPodcast)),"Following","Follow"));document.querySelectorAll("[data-save-episode]").forEach(b=>paint(b,es.has(String(b.dataset.saveEpisode)),"Saved","Save"));document.querySelectorAll("[data-favorite-episode]").forEach(b=>paint(b,fs.has(String(b.dataset.favoriteEpisode)),"Favorited","Favorite"));document.querySelectorAll("[data-follow-member]").forEach(b=>paint(b,ms.has(String(b.dataset.followMember)),"Following","Follow"))}
window.CrowRulesMemberActions={toggleEpisodeFavorite,togglePodcastFollow,toggleEpisodeSave,toggleMemberFollow,markNotificationRead,bind,hydrate};
const boot=()=>{bind();setTimeout(hydrate,250)};if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else boot();window.addEventListener("crowrules:member-state",e=>{if(["ready","database-change","focus-sync","visibility-sync"].includes(e.detail?.reason))hydrate()});
})();