/* CrowRules Podcasting — Unified Data/Application Layer 2.0 */
(function(){
"use strict";
if(window.CrowRulesData)return;
const CFG={url:window.CROWRULES_SUPABASE_URL||"https://cevylpnoexugwgygvtgu.supabase.co",key:window.CROWRULES_SUPABASE_PUBLISHABLE_KEY||"",refreshMs:120000};
let db=null,session=null,channel=null,readyPromise=null,timer=null;
const state={status:"booting",user:null,session:null,error:null,lastSync:null,realtime:"offline",permission:"guest"};
const channels=new Map(),listeners=new Set();
function emit(){bindStates();const snapshot=structuredClone(state);listeners.forEach(fn=>{try{fn(snapshot)}catch(_){}});window.dispatchEvent(new CustomEvent("crowrules:data-state",{detail:snapshot}))}
function setStatus(status,error=null){state.status=status;state.error=error?String(error.message||error):null;state.permission=state.user?"authenticated":"guest";emit()}
async function waitForClient(){for(let i=0;i<60;i++){if(window.supabaseClient)return window.supabaseClient;if(window.supabase?.createClient&&CFG.key){db=window.supabase.createClient(CFG.url,CFG.key);return db}await new Promise(r=>setTimeout(r,100))}throw new Error("Supabase client unavailable")}
async function boot(){if(readyPromise)return readyPromise;readyPromise=(async()=>{try{setStatus("loading");db=await waitForClient();const r=await db.auth.getSession();session=r.data?.session||null;state.session=session;state.user=session?.user||null;if(!state.user){state.lastSync=new Date().toISOString();setStatus("guest");return state}await startRealtime();state.lastSync=new Date().toISOString();setStatus("ready");timer=setInterval(()=>refresh(),refreshMs);return state}catch(e){setStatus("error",e);return state}})();return readyPromise}
async function getUser(){await boot();return state.user||null}
async function getAccessToken(){await boot();return session?.access_token||null}
async function requireAuth(){return guard("member")}
async function getClientAsync(){await boot();if(!db)throw new Error("Supabase client unavailable");return db}
async function query(table,options={}){const client=await getClientAsync();let q=client.from(table);if(options.select)q=q.select(options.select);if(options.eq)for(const [k,v] of Object.entries(options.eq))q=q.eq(k,v);if(options.order)q=q.order(options.order.column,{ascending:options.order.ascending!==false});if(options.limit)q=q.limit(options.limit);if(options.single)q=q.single();return q}
function createStateElement(type,message){const el=document.createElement("div");el.className="cr-data-"+type;el.setAttribute("role",type==="error"?"alert":"status");el.textContent=message||({loading:"Loading…",error:"Something went wrong.",empty:"Nothing here yet.",auth:"Sign in to continue.",forbidden:"You do not have permission to view this area."}[type]||"");return el}
function renderState(container,type,message){if(!container)return null;container.querySelectorAll(":scope > .cr-data-loading,:scope > .cr-data-error,:scope > .cr-data-empty,:scope > .cr-data-auth,:scope > .cr-data-forbidden").forEach(e=>e.remove());return container.prepend(createStateElement(type,message))}
function bindStates(root=document){root.querySelectorAll("[data-cr-auth]").forEach(el=>{el.hidden=state.user?el.dataset.crAuth==="guest":el.dataset.crAuth==="required"})}
function subscribe(nameOrTable,filterOrHandler,maybeHandler){let name=nameOrTable,filter=filterOrHandler,handler=maybeHandler;if(typeof filterOrHandler==="function"){handler=filterOrHandler;filter=null}if(!db||!state.user)return()=>{};if(channels.has(name))channels.get(name).stop();const ch=db.channel("crowrules-data-"+name+"-"+Date.now()).on("postgres_changes",{event:"*",schema:"public",table:name.includes(".")?name.split(".")[0]:name,filter},handler);const stop=()=>{try{db.removeChannel(ch)}catch(_){}channels.delete(name)};channels.set(name,{channel:ch,stop});ch.subscribe(s=>{if(s==="CHANNEL_ERROR"||s==="TIMED_OUT")state.realtime="disconnected";else if(s==="SUBSCRIBED")state.realtime="connected";emit()});return stop}
function unsubscribe(name){channels.get(name)?.stop()}
function unsubscribeAll(){channels.forEach(x=>x.stop());channels.clear();if(channel&&db){try{db.removeChannel(channel)}catch(_){}}channel=null;state.realtime="offline";emit()}
async function refresh(){if(!db)return boot();try{const r=await db.auth.getSession();const next=r.data?.session||null,previous=state.user?.id||null;session=next;state.session=next;state.user=next?.user||null;state.lastSync=new Date().toISOString();if(previous&&previous!==state.user?.id)unsubscribeAll();if(!state.user){if(timer){clearInterval(timer);timer=null}unsubscribeAll();setStatus("guest");return state}if(!channel)await startRealtime();if(!timer)timer=setInterval(()=>refresh(),refreshMs);setStatus("ready");return state}catch(e){setStatus("error",e);return state}}
async function startRealtime(){if(!db||!state.user||channel)return;const id=state.user.id;channel=db.channel("crowrules-platform-data-"+id.slice(0,12));channel.on("postgres_changes",{event:"*",schema:"public",table:"podcast_notifications",filter:"user_id=eq."+id},()=>emit());channel.subscribe(s=>{state.realtime=s==="SUBSCRIBED"?"connected":(s==="CHANNEL_ERROR"||s==="TIMED_OUT"?"disconnected":state.realtime);emit()})}
async function guard(permission){const u=await getUser();if(!u){const e=new Error("Authentication required");e.code="AUTH_REQUIRED";throw e}if(permission==="member")return u;const db=await getClientAsync();let ok=true;if(permission==="creator"){const r=await db.from("creator_profiles").select("id").eq("user_id",u.id).maybeSingle();ok=!!r.data}else if(permission==="premium"){const r=await db.from("cr_podcast_entitlements").select("id").eq("member_user_id",u.id).eq("status","active").limit(1);if(r.error)throw r.error;ok=!!r.data?.length}else if(permission==="payouts"){const r=await db.from("cr_podcast_stripe_accounts").select("payouts_enabled").eq("user_id",u.id).maybeSingle();ok=!!r.data?.payouts_enabled}else if(permission==="admin"){const r=await db.from("cr_admins").select("id").eq("user_id",u.id).maybeSingle();ok=!!r.data}if(!ok)throw Object.assign(new Error(permission+" permission required"),{code:"PERMISSION_DENIED",permission});return u}
async function run(task){try{return{data:await task(),error:null,status:"success"}}catch(error){return{data:null,error,status:error?.code==="PERMISSION_DENIED"?"forbidden":error?.code==="AUTH_REQUIRED"?"auth":"error"}}}
async function execute(task,options={}){options.onState?.({data:null,error:null,status:"loading"});try{const data=await task();const result={data,error:null,status:"success"};options.onState?.(result);return result}catch(error){const result={data:null,error,status:error?.code==="PERMISSION_DENIED"?"forbidden":error?.code==="AUTH_REQUIRED"?"auth":"error"};options.onState?.(result);return result}}
async function signOut(){unsubscribeAll();if(!db)return;await db.auth.signOut();await refresh()}
window.CrowRulesData={version:"2.0",ready:boot(),createStateElement,renderState,bindStates,getClient:()=>db,getClientAsync,getAccessToken,getState:()=>structuredClone(state),getUser,requireAuth,query,subscribe,unsubscribe,unsubscribeAll,guard,run,execute,refresh,signOut,on:fn=>{listeners.add(fn);return()=>listeners.delete(fn)}};
window.CrowRulesData.ready.then(()=>{if(db?.auth)db.auth.onAuthStateChange(()=>refresh())}).catch(()=>{});
})();