(()=>{
'use strict';
if(window.__CROW_PODCASTING_V12__)return;window.__CROW_PODCASTING_V12__=true;
const BASE='https://crowrulesentertainment-oss.github.io/podcasting/';
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||c));
const client=()=>window.CROW_SUPABASE||null;
const getUser=async()=>{const sb=client();if(!sb)return null;const r=await sb.auth.getUser();return r.data?.user||null};
const img=(url,emoji='🎙️')=>url?'<img src="'+esc(url)+'" alt="">':'<div class="crh-art">'+emoji+'</div>';
const card=(x,type='Podcast')=>'<a class="crh-card" href="'+esc(x.href||'#')+'">'+img(x.image)+'<div class="crh-card-body"><b>'+esc(x.title||'Untitled')+'</b><small>'+esc(x.meta||type)+'</small><span>'+esc(x.desc||'')+'</span></div></a>';
function addCSS(){if(document.getElementById('cr12css'))return;const l=document.createElement('link');l.id='cr12css';l.rel='stylesheet';l.href=BASE+'css/podcasting-v12.css?v=20261004-13';document.head.appendChild(l)}
function openSearch(){if(document.getElementById('cr12Search'))return;const o=document.createElement('div');o.id='cr12Search';o.className='cr12-overlay';o.innerHTML='<section class="cr12-search-card"><button class="cr12-close" aria-label="Close">×</button><div class="cr12-kicker">CROWRULES PODCASTING INTELLIGENCE</div><h2>Search the Podcast Universe</h2><p>Podcasts, episodes and creators — one signal.</p><input id="cr12SearchInput" class="cr12-input" autocomplete="off" placeholder="Search podcasts, episodes, creators…"><div id="cr12SearchMeta" class="cr12-muted">Start typing to search.</div><div id="cr12SearchResults" class="cr12-results"></div></section>';document.body.appendChild(o);const q=o.querySelector('#cr12SearchInput');o.querySelector('.cr12-close').onclick=()=>o.remove();o.onclick=e=>{if(e.target===o)o.remove()};q.oninput=()=>search(q.value);q.focus()}
let timer;async function search(term){clearTimeout(timer);timer=setTimeout(async()=>{const sb=client(),box=document.getElementById('cr12SearchResults'),meta=document.getElementById('cr12SearchMeta');if(!sb||term.trim().length<2){if(meta)meta.textContent='Start typing to search.';if(box)box.innerHTML='';return}meta.textContent='Searching…';try{const t='%'+term.trim().replace(/[%_]/g,'')+'%';const [p,e,c]=await Promise.all([sb.from('podcasts').select('id,title,slug,description,artwork_url,status').ilike('title',t).eq('status','published').limit(8),sb.from('podcast_episodes').select('id,title,description,thumbnail_url,status').ilike('title',t).eq('status','published').limit(8),sb.from('creators').select('id,name,display_name,slug,bio,avatar_url,is_active').or('name.ilike.'+t+',display_name.ilike.'+t).eq('is_active',true).limit(8)]);const rows=[];(p.data||[]).forEach(x=>rows.push({title:x.title,desc:x.description,meta:'Podcast',image:x.artwork_url,href:'podcast.html?slug='+encodeURIComponent(x.slug||x.id)}));(e.data||[]).forEach(x=>rows.push({title:x.title,desc:x.description,meta:'Episode',image:x.thumbnail_url,href:'episode.html?id='+encodeURIComponent(x.id)}));(c.data||[]).forEach(x=>rows.push({title:x.display_name||x.name,desc:x.bio,meta:'Creator',image:x.avatar_url,href:'creator.html?slug='+encodeURIComponent(x.slug||x.id)}));meta.textContent=rows.length?rows.length+' results':'No matches found';box.innerHTML=rows.map(x=>card(x,x.meta)).join('')||'<div class="cr12-empty">Try another title or creator.</div>'}catch(e){meta.textContent='Search unavailable';box.innerHTML='<div class="cr12-empty">'+esc(e.message||'Connection error')+'</div>'}},180)}
function cleanSite(){const navs=[...document.querySelectorAll('[data-nav]')];const owner=navs.find(n=>n.hasAttribute('data-nav-owner'))||navs[0];navs.forEach(n=>{if(n!==owner)n.remove()});if(owner&&!owner.hasAttribute('data-nav-owner'))owner.setAttribute('data-nav-owner','crowrules-podcasting-v12-shell');document.querySelectorAll('main:not(.scene)').forEach(m=>m.classList.add('cr12-main-shell'));document.documentElement.classList.add('cr12-site-ready')}\nfunction navShell(){if(document.getElementById('cr12SiteNav'))return;const path=(location.pathname.split('/').pop()||'index.html').toLowerCase();const items=[['home.html','HOME','⌂'],['discover.html','DISCOVER','◈'],['podcasts.html','PODCASTS','◉'],['episodes.html','EPISODES','▶'],['library.html','LIBRARY','▣'],['creator-dashboard.html','CREATOR','✦'],['notifications.html','NOTIFICATIONS','◌'],['account.html','ACCOUNT','◎']];const n=document.createElement('nav');n.id='cr12SiteNav';n.className='cr12-nav';n.setAttribute('aria-label','CrowRules Podcasting navigation');n.innerHTML='<a class="cr12-brand" href="'+BASE+'home.html"><strong>CROWRULES</strong><span>PODCASTING</span></a><div class="cr12-nav-links">'+items.map(([href,label,icon])=>'<a href="'+BASE+href+'" class="'+(path===href?'active':'')+'"><i>'+icon+'</i><span>'+label+'</span></a>').join('')+'</div><div class="cr12-nav-tools"><button id="cr12NavSearch" aria-label="Search">⌕</button><a href="'+BASE+'account.html" aria-label="Account">◎</a></div>';document.body.prepend(n);document.getElementById('cr12NavSearch').addEventListener('click',openSearch);}function shell(){cleanSite();addCSS();navShell();if(!document.getElementById('cr12SearchButton')){const b=document.createElement('button');b.id='cr12SearchButton';b.className='cr12-fab';b.title='Podcast Intelligence Search';b.innerHTML='⌕ <span>SEARCH</span>';b.onclick=openSearch;document.body.appendChild(b)}if(!document.getElementById('cr12HomeButton')&&!location.pathname.endsWith('/home.html')){const a=document.createElement('a');a.id='cr12HomeButton';a.className='cr12-home-link';a.href=BASE+'home.html';a.innerHTML='⌂ <span>PODCAST HOME</span>';document.body.appendChild(a)}}function renderSection(id,title,sub,html){const el=document.getElementById(id);if(el)el.innerHTML='<div class="crh-section-head"><div><div class="cr12-kicker">'+esc(title)+'</div><h2>'+esc(sub)+'</h2></div></div><div class="crh-row">'+html+'</div>'}
async function waitForClient(ms=9000){const start=Date.now();while(Date.now()-start<ms){if(client())return client();await new Promise(r=>setTimeout(r,150))}return null}\nasync function home(){const root=document.querySelector('[data-crow-personal-home]');if(!root)return;const sb=await waitForClient(),u=await getUser().catch(()=>null);if(!sb||!u){root.innerHTML='<div class="crh-login"><div class="cr12-kicker">PERSONAL PODCAST HOME</div><h1>Your Podcast Home.</h1><p>Sign in to unlock listening history, follows, recommendations, notifications and realtime activity.</p><a href="account.html" class="crh-btn">Sign in to CrowRules</a></div>';return}
root.innerHTML='<div class="crh-hero"><div><div class="cr12-kicker">CROWRULES PODCASTING • PERSONAL HOME</div><h1>Your Podcast <span>Signal.</span></h1><p id="crhWelcome">Building your listening universe…</p></div><div class="crh-actions"><button id="crhRefresh" class="crh-btn">↻ Refresh</button><button id="crhSearch" class="crh-btn primary">⌕ Search</button></div></div><div class="crh-layout"><div class="crh-main"><section id="crhContinue" class="crh-section"></section><section id="crhBecause" class="crh-section"></section><section id="crhFollowed" class="crh-section"></section><section id="crhTrending" class="crh-section"></section><section id="crhCreators" class="crh-section"></section><section id="crhRecent" class="crh-section"></section></div><aside class="crh-rail"><section id="crhNotifications" class="crh-rail-card"></section><section id="crhPrefs" class="crh-rail-card"></section><section id="crhActivity" class="crh-rail-card"></section></aside></div>';
document.getElementById('crhSearch').onclick=openSearch;document.getElementById('crhRefresh').onclick=()=>loadHome(true);await loadHome();
async function loadHome(){const sb=client()||await waitForClient(),u=await getUser().catch(()=>null);if(!sb||!u)return;const welcome=document.getElementById('crhWelcome');if(welcome)welcome.textContent='Personalized from your listening history and followed shows.';
const follows=(await sb.from('podcast_follows').select('podcast_id,created_at').eq('user_id',u.id).order('created_at',{ascending:false}).limit(50)).data||[];const followIds=[...new Set(follows.map(x=>x.podcast_id))];
const listens=(await sb.from('podcast_listens').select('episode_id,created_at,seconds_listened,completed').eq('user_id',u.id).order('created_at',{ascending:false}).limit(100)).data||[];const recentEpisodeIds=[...new Set(listens.map(x=>x.episode_id))];
const prog=(await sb.from('cr_podcast_playback_progress').select('episode_id,position_seconds,duration_seconds,progress_percent,last_played_at').eq('user_id',u.id).eq('completed',false).order('last_played_at',{ascending:false}).limit(8))).data||[];const progressIds=[...new Set(prog.map(x=>x.episode_id))];
const allEpIds=[...new Set([...progressIds,...recentEpisodeIds])].slice(0,100);let eps=[];if(allEpIds.length){eps=(await sb.from('podcast_episodes').select('id,title,slug,description,podcast_id,thumbnail_url,status,published_at,play_count,tags').in('id',allEpIds).eq('status','published')).data||[]}
const podcastIds=[...new Set([...followIds,...eps.map(x=>x.podcast_id)])];let pods=[];if(podcastIds.length){pods=(await sb.from('podcasts').select('id,title,slug,description,artwork_url,category,total_plays,creator_id,status').in('id',podcastIds).eq('status','published')).data||[]}
const followed=pods.filter(p=>followIds.includes(p.id));
const followedCategories=[...new Set(followed.map(p=>p.category).filter(Boolean))];const recentCategories=eps.map(e=>pods.find(p=>p.id===e.podcast_id)?.category).filter(Boolean);const taste=[...new Set([...recentCategories,...followedCategories])].slice(0,5);
const seen=new Set(podcastIds);let catalog=(await sb.from('podcasts').select('id,title,slug,description,artwork_url,category,total_plays,creator_id,status').eq('status','published').order('total_plays',{ascending:false}).limit(40))).data||[];
const because=catalog.filter(p=>!seen.has(p.id)&&taste.some(c=>c===p.category)).slice(0,6);const trending=followed.slice().sort((a,b)=>Number(b.total_plays||0)-Number(a.total_plays||0)).slice(0,6);const recent=eps.slice().sort((a,b)=>new Date(b.published_at||0)-new Date(a.published_at||0)).slice(0,6);
let creatorIds=[...new Set([...because,...catalog].map(p=>p.creator_id).filter(Boolean))].filter(id=>{const own=pods.find(p=>p.creator_id===id);return !own||!followIds.includes(own.id)}).slice(0,10);let creators=[];if(creatorIds.length)creators=(await sb.from('creators').select('id,name,display_name,slug,bio,avatar_url,is_active').in('id',creatorIds).eq('is_active',true)).data||[];
renderSection('crhContinue','CONTINUE LISTENING','Pick up where you left off',progressIds.map(id=>{const e=eps.find(x=>x.id===id);if(!e)return '';const p=prog.find(x=>x.episode_id===id)||{};const pct=Math.max(0,Math.min(100,Number(p.progress_percent||((p.position_seconds||0)/(p.duration_seconds||e.duration_seconds||1)*100))));return card({title:e.title,description:e.description,image:e.thumbnail_url,meta:Math.round(pct)+'% complete',href:'episode.html?id='+encodeURIComponent(e.id)},'Episode')}).join('')||'<div class="cr12-empty">Start an episode and it will appear here.</div>');
renderSection('crhBecause','BECAUSE YOU LISTENED','Recommendations based on your actual listening',because.map(p=>card({title:p.title,desc:p.description,image:p.artwork_url,meta:p.category||'Recommended',href:'podcast.html?slug='+encodeURIComponent(p.slug||p.id)})).join('')||'<div class="cr12-empty">Keep listening to build your recommendations.</div>');
renderSection('crhFollowed','FOLLOWED SHOWS','Your followed podcast network',followed.map(p=>card({title:p.title,desc:p.description,image:p.artwork_url,meta:(p.is_live?'● LIVE · ':'')+'Followed',href:'podcast.html?slug='+encodeURIComponent(p.slug||p.id)})).join('')||'<div class="cr12-empty">Follow a show to build your personal network.</div>');
renderSection('crhTrending','TRENDING FOR YOU','Most-played among the shows you follow',trending.map(p=>card({title:p.title,desc:p.description,image:p.artwork_url,meta:Number(p.total_plays||0).toLocaleString()+' plays',href:'podcast.html?slug='+encodeURIComponent(p.slug||p.id)})).join('')||'<div class="cr12-empty">Trending will appear after you follow shows.</div>');
renderSection('crhCreators','CREATOR RECOMMENDATIONS','Voices that match your listening trail',creators.slice(0,6).map(c=>card({title:c.display_name||c.name,desc:c.bio,image:c.avatar_url,meta:'Creator',href:'creator.html?slug='+encodeURIComponent(c.slug||c.id)},'Creator')).join('')||'<div class="cr12-empty">Creator recommendations will grow with the network.</div>');
renderSection('crhRecent','RECENTLY PLAYED','Your listening history',recent.map(e=>{const p=pods.find(x=>x.id===e.podcast_id);return card({title:e.title,desc:p?.title||'',image:e.thumbnail_url,meta:new Date(e.published_at||Date.now()).toLocaleDateString(),href:'episode.html?id='+encodeURIComponent(e.id)},'Episode')}).join('')||'<div class="cr12-empty">No listening history yet.</div>');
await renderNotifications(sb,u);await renderPrefs(sb,u);await renderActivity(sb,u,followIds);}
async function renderNotifications(sb,u){const el=document.getElementById('crhNotifications');if(!el)return;const r=await sb.from('crowrules_notifications').select('id,type,title,body,action_url,is_read,created_at').eq('user_id',u.id).eq('division','podcasting').order('created_at',{ascending:false}).limit(8);const rows=r.data||[];el.innerHTML='<div class="cr12-kicker">NOTIFICATION CENTER</div><h3>Signals</h3>'+(rows.length?rows.map(x=>'<a class="crh-note '+(x.is_read?'':'unread')+'" href="'+esc(x.action_url||'#')+'"><b>'+esc(x.title||x.type||'Podcasting update')+'</b><span>'+esc(x.body||'')+'</span><small>'+new Date(x.created_at).toLocaleString()+'</small></a>').join(''):'<div class="cr12-empty">No new signals.</div>')}
async function renderPrefs(sb,u){const el=document.getElementById('crhPrefs');if(!el)return;const r=await sb.from('podcast_notification_preferences').select('follows,new_episodes,comments,reactions,live_enabled,email_enabled,push_enabled,quiet_hours_enabled').eq('user_id',u.id).maybeSingle();const p=r.data||{follows:true,new_episodes:true,comments:true,reactions:true,live_enabled:true,email_enabled:false,push_enabled:false,quiet_hours_enabled:false};const fields=[['follows','Follow activity'],['new_episodes','New episodes'],['comments','Comments'],['reactions','Reactions'],['live_enabled','Live signals'],['email_enabled','Email'],['push_enabled','Push'],['quiet_hours_enabled','Quiet hours']];el.innerHTML='<div class="cr12-kicker">NOTIFICATION CONTROL</div><h3>Preferences</h3><div class="crh-prefs">'+fields.map(([k,label])=>'<label><span>'+label+'</span><input type="checkbox" data-pref="'+k+'" '+(p[k]?'checked':'')+'></label>').join('')+'</div><small class="crh-save" id="crhPrefStatus">Changes save to your account.</small>';el.querySelectorAll('[data-pref]').forEach(input=>input.onchange=async()=>{const key=input.dataset.pref;const value=input.checked;const payload={user_id:u.id,[key]:value,updated_at:new Date().toISOString()};const res=await sb.from('podcast_notification_preferences').upsert(payload,{onConflict:'user_id'});document.getElementById('crhPrefStatus').textContent=res.error?'Could not save this preference.':'Preference saved.'})}
async function renderActivity(sb,u,followIds){const el=document.getElementById('crhActivity');if(!el)return;const [f,n,e]=await Promise.all([sb.from('podcast_follows').select('created_at,podcast_id').eq('user_id',u.id).order('created_at',{ascending:false}).limit(6),sb.from('crowrules_notifications').select('created_at,title,type').eq('user_id',u.id).eq('division','podcasting').order('created_at',{ascending:false}).limit(6),sb.from('podcast_listens').select('created_at,episode_id,seconds_listened').eq('user_id',u.id).order('created_at',{ascending:false}).limit(6)]);const items=[];(f.data||[]).forEach(x=>items.push({t:x.created_at,k:'FOLLOWED',s:'A show joined your network'}));(n.data||[]).forEach(x=>items.push({t:x.created_at,k:'SIGNAL',s:x.title||x.type||'Podcasting update'}));(e.data||[]).forEach(x=>items.push({t:x.created_at,k:'LISTENED',s:Math.round(Number(x.seconds_listened||0)/60)+' min listened'}));items.sort((a,b)=>new Date(b.t)-new Date(a.t));el.innerHTML='<div class="cr12-kicker">LIVE ACTIVITY</div><h3>Activity rail</h3>'+ (items.length?items.slice(0,12).map(x=>'<div class="crh-activity"><i></i><b>'+esc(x.k)+'</b><span>'+esc(x.s)+'</span><small>'+new Date(x.t).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})+'</small></div>').join(''):'<div class="cr12-empty">Your live activity will appear here.</div>')}
}
function realtime(){const sb=client();if(!sb)return;const ch=sb.channel('podcasting-v12-1-personal-home').on('postgres_changes',{event:'*',schema:'public',table:'podcast_follows'},()=>document.dispatchEvent(new CustomEvent('crh:refresh'))).on('postgres_changes',{event:'*',schema:'public',table:'podcast_listens'},()=>document.dispatchEvent(new CustomEvent('crh:refresh'))).on('postgres_changes',{event:'*',schema:'public',table:'podcast_episodes'},()=>document.dispatchEvent(new CustomEvent('crh:refresh'))).on('postgres_changes',{event:'*',schema:'public',table:'crowrules_notifications'},()=>document.dispatchEvent(new CustomEvent('crh:refresh'))).subscribe();window.CROW_PODCASTING_INTELLIGENCE={channel:ch,search:openSearch}}
async function start(){cleanSite();addCSS();shell();const root=document.querySelector('[data-crow-personal-home]');if(root)home().catch(console.warn);realtime();document.addEventListener('crh:refresh',()=>{if(document.querySelector('[data-crow-personal-home]'))home().catch(()=>{})})}
start();
})();
