(()=>{"use strict";
const $=id=>document.getElementById(id),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c])),fmt=v=>Number(v||0).toLocaleString();
let sb,u,creator,snaps=[],range=30,rt;
async function client(){if(window.CROW_SUPABASE)return window.CROW_SUPABASE;if(window.CROW_SUPABASE_READY)return await window.CROW_SUPABASE_READY;return null}
async function load(){
 sb=await client();if(!sb)return;u=(await sb.auth.getUser()).data?.user;if(!u)return;
 let q=await sb.rpc("get_my_podcast_creator_id");if(q.error||!q.data)return;creator=q.data;
 const s=await sb.from("creator_intelligence_snapshots").select("*").eq("creator_id",creator).order("snapshot_date",{ascending:true}).limit(400);snaps=s.error?[]:(s.data||[]);
 render();
 realtime();
}
function filtered(){const cut=new Date();cut.setDate(cut.getDate()-range);return snaps.filter(x=>new Date(x.snapshot_date)>=cut)}
function delta(a,b,k){return Number(b?.[k]||0)-Number(a?.[k]||0)}
function render(){
 const rows=filtered(), latest=rows[rows.length-1]||snaps[snaps.length-1]||{};
 const first=rows[0]||latest;
 let health=Number(latest.health_score||0);if(!health&&latest.id)health=Math.max(0,Math.min(100,Math.round(Number(latest.audience_growth||0)+50)));
 const growth=delta(first,latest,"followers")+delta(first,latest,"subscribers");
 const html='<section id="v17Command" class="v17-section"><div class="v17-head"><div><span>V17 · CREATOR ANALYTICS COMMAND CENTER</span><h2>Audience intelligence</h2><p>Historical growth, listening momentum, episode performance and live creator signals.</p></div><div class="v17-range"><button data-r="7">7D</button><button data-r="30">30D</button><button data-r="90">90D</button><button data-r="365">1Y</button></div></div><div class="v17-kpis"><div><b>'+fmt(latest.followers)+'</b><small>Followers</small><em>'+signed(delta(first,latest,"followers"))+'</em></div><div><b>'+fmt(latest.subscribers)+'</b><small>Subscribers</small><em>'+signed(delta(first,latest,"subscribers"))+'</em></div><div><b>'+fmt(latest.minutes_listened)+'</b><small>Minutes listened</small><em>'+signed(delta(first,latest,"minutes_listened"))+'</em></div><div><b>'+fmt(latest.plays)+'</b><small>Plays</small><em>'+signed(delta(first,latest,"plays"))+'</em></div><div><b>'+health+'</b><small>Creator health</small><em>'+healthLabel(health)+'</em></div></div><div class="v17-grid"><div class="v17-panel"><h3>Audience growth</h3><div class="v17-chart">'+line(rows,"followers","subscribers")+'</div></div><div class="v17-panel"><h3>Listening momentum</h3><div class="v17-chart">'+line(rows,"minutes_listened","plays")+'</div></div></div><div class="v17-grid"><div class="v17-panel"><h3>Milestones</h3><div id="v17Milestones">'+milestones(rows)+'</div></div><div class="v17-panel"><h3>Realtime alerts</h3><div id="v17Alerts17">Loading live signals…</div></div></div><div class="v17-panel"><h3>Episode comparison</h3><div id="v17Episodes17">Loading episode performance…</div></div></section>';
 const host=$("dashboard")||document.querySelector("main");if(!host)return;let old=$("v17Command");if(old)old.outerHTML=html;else host.insertAdjacentHTML("beforeend",html);
 document.querySelectorAll("[data-r]").forEach(b=>b.onclick=()=>{range=Number(b.dataset.r);render()});loadEpisodes();loadAlerts();
}
function signed(n){n=Number(n||0);return (n>0?"+":"")+fmt(n)}
function healthLabel(n){return n>=80?"Strong":n>=60?"Healthy":n>=40?"Watch":"Needs attention"}
function line(rows,a,b){if(!rows.length)return'<div class="v17-empty">Historical snapshots will appear as the creator intelligence system records daily data.</div>';const max=Math.max(1,...rows.map(x=>Math.max(Number(x[a]||0),Number(x[b]||0))));return'<div class="v17-spark">'+rows.map((x,i)=>'<i title="'+esc(x.snapshot_date)+' · '+esc(a)+': '+fmt(x[a])+'" style="height:'+Math.max(4,Math.round(Number(x[a]||0)/max*100))+'%"></i>').join("")+'</div><div class="v17-legend"><span>'+esc(a.replaceAll("_"," "))+'</span><span>'+esc(b.replaceAll("_"," "))+'</span></div>'}
function milestones(rows){if(!rows.length)return'<div class="v17-empty">No historical milestones yet.</div>';const latest=rows[rows.length-1],vals=[];for(const [k,label] of [["followers","followers"],["subscribers","subscribers"],["plays","plays"]]){const n=Number(latest[k]||0);for(const m of [10,25,50,100,250,500,1000,5000,10000])if(n>=m)vals.push('<span>✓ '+m.toLocaleString()+" "+label+"</span>")}return vals.length?'<div class="v17-milestones">'+[...new Set(vals)].slice(-9).join("")+'</div>':'<div class="v17-empty">Your first audience milestones will appear here.</div>'}
async function loadEpisodes(){const host=$("v17Episodes17");if(!host||!creator)return;const p=await sb.from("podcasts").select("id").eq("creator_id",creator);if(p.error||!p.data?.length){host.innerHTML='<div class="v17-empty">No podcasts connected.</div>';return}const e=await sb.from("podcast_episodes").select("id,title,play_count,published_at,podcast_id,duration_seconds").in("podcast_id",p.data.map(x=>x.id)).order("play_count",{ascending:false}).limit(20);if(e.error||!e.data?.length){host.innerHTML='<div class="v17-empty">No episode performance data yet.</div>';return}const max=Math.max(1,...e.data.map(x=>Number(x.play_count||0)));host.innerHTML='<div class="v17-episode-list">'+e.data.map(x=>'<div><span><b>'+esc(x.title)+'</b><small>'+fmt(x.play_count)+' plays</small></span><i style="width:'+Math.max(2,Math.round(Number(x.play_count||0)/max*100))+'%"></i></div>').join("")+'</div>'}
async function loadAlerts(){const host=$("v17Alerts17");if(!host)return;const q=await sb.from("creator_realtime_alerts").select("*").eq("creator_id",creator).order("created_at",{ascending:false}).limit(8);if(q.error||!q.data?.length){host.innerHTML='<div class="v17-empty">No live creator events yet.</div>';return}host.innerHTML=q.data.map(x=>'<div class="v17-alert"><b>'+esc(x.title||x.alert_type||"Creator event")+'</b><p>'+esc(x.message||"New creator activity detected.")+'</p><small>'+new Date(x.created_at).toLocaleString()+'</small></div>').join("")}
function realtime(){if(rt)return;try{rt=sb.channel("cr-v17-"+creator).on("postgres_changes",{event:"*",schema:"public",table:"creator_intelligence_snapshots",filter:"creator_id=eq."+creator},()=>load()).on("postgres_changes",{event:"*",schema:"public",table:"creator_realtime_alerts",filter:"creator_id=eq."+creator},()=>{loadAlerts()}).on("postgres_changes",{event:"*",schema:"public",table:"podcast_listens"},()=>loadEpisodes()).on("postgres_changes",{event:"*",schema:"public",table:"podcast_follows"},()=>load()).on("postgres_changes",{event:"*",schema:"public",table:"podcast_subscriptions"},()=>load()).subscribe()}catch{}}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>setTimeout(load,1200));else setTimeout(load,1200);
})();
(function(){var s=document.createElement('script');s.src='js/podcasting-v18.js?v=20261004-18';s.defer=true;document.head.appendChild(s)})();