/* CrowRules Podcasting — sitewide shell v2 */
(()=>{"use strict";
const SUPABASE_URL="https://cevylpnoexugwgygvtgu.supabase.co",SUPABASE_KEY="sb_publishable_AdfM5y6RqvF3tbvEVzDZSg_JuGTQLD-";
const sb=window.supabase?.createClient(SUPABASE_URL,SUPABASE_KEY);
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const base=location.pathname.split("/").pop()||"index.html";
const nav=()=>{let h=document.querySelector(".site-header");if(h)h.classList.add("sitewide-header");if(!h){h=document.createElement("header");h.className="sitewide-header";document.body.prepend(h)}
h.innerHTML='<a class="sitewide-brand" href="home.html"><span class="sitewide-mark">C</span><span><b>CrowRules</b><small>Podcasting</small></span></a><nav class="sitewide-nav"><a href="home.html">Home</a><a href="discover.html">Discover</a><a href="rankings.html">Rankings</a><a href="library.html">My Library</a><a href="creator-studio.html">Creator Studio</a><a href="membership.html">Membership</a><a href="community.html">Community</a><a href="launch.html">Launch</a><a data-site-account href="auth.html">Sign In</a><a href="https://crowrulesentertainment-oss.github.io/crowrulesentertainment/">CrowRules</a></nav><button class="sitewide-menu" aria-label="Open navigation">☰</button>';
const menu=h.querySelector(".sitewide-menu"),n=h.querySelector(".sitewide-nav");menu.onclick=()=>n.classList.toggle("open");n.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>n.classList.remove("open")));
return h};
const player=()=>{if(document.querySelector(".sitewide-player"))return document.querySelector(".sitewide-player");const p=document.createElement("div");p.className="sitewide-player";p.innerHTML='<img class="player-art" alt=""><div class="player-main"><div class="player-title">CrowRules Podcasting</div><div class="player-author">Ready to listen</div><input class="player-progress" type="range" min="0" max="100" value="0" aria-label="Audio progress"></div><div class="player-time">0:00 / 0:00</div><button class="player-btn primary player-toggle" aria-label="Play">▶</button><button class="player-close" aria-label="Close player">×</button><audio preload="metadata"></audio>';document.body.appendChild(p);return p};
let p,a;
function fmt(v){if(!Number.isFinite(v)||v<0)return"0:00";const m=Math.floor(v/60),s=Math.floor(v%60);return m+":"+String(s).padStart(2,"0")}
function api(){p=p||player();a=p.querySelector("audio");return{p,a}}
function play(item){const x=api(),same=x.a.src===item.url;if(!same){x.a.src=item.url;x.a.dataset.title=item.title||"CrowRules Podcasting";x.a.dataset.author=item.author||"CrowRules Creator";x.a.dataset.art=item.artwork||"";x.a.currentTime=0}x.p.querySelector(".player-title").textContent=item.title||"CrowRules Podcasting";x.p.querySelector(".player-author").textContent=item.author||"CrowRules Creator";const art=x.p.querySelector(".player-art");art.src=item.artwork||"data:image/svg+xml;charset=UTF-8,"+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="80" height="80"><rect width="80" height="80" fill="#111722"/><text x="40" y="48" text-anchor="middle" fill="#5ee7ff" font-size="22" font-family="Arial">CR</text></svg>');x.p.classList.add("visible");localStorage.setItem("crowrules_audio",JSON.stringify(item));x.a.play().catch(()=>{});updateButton()}
function updateButton(){const x=api();x.p.querySelector(".player-toggle").textContent=x.a.paused?"▶":"Ⅱ";x.p.querySelector(".player-toggle").setAttribute("aria-label",x.a.paused?"Play":"Pause")}
function bind(){const x=api(),range=x.p.querySelector(".player-progress");x.p.querySelector(".player-toggle").onclick=()=>x.a.paused?x.a.play():x.a.pause();x.p.querySelector(".player-close").onclick=()=>{x.a.pause();x.p.classList.remove("visible")};range.oninput=()=>{if(x.a.duration)x.a.currentTime=(Number(range.value)/100)*x.a.duration};x.a.addEventListener("play",updateButton);x.a.addEventListener("pause",updateButton);x.a.addEventListener("timeupdate",()=>{if(x.a.duration){range.value=x.a.currentTime/x.a.duration*100;x.p.querySelector(".player-time").textContent=fmt(x.a.currentTime)+" / "+fmt(x.a.duration)}});x.a.addEventListener("ended",()=>{range.value=0;updateButton()});if("mediaSession"in navigator){x.a.addEventListener("loadedmetadata",()=>{try{navigator.mediaSession.metadata=new MediaMetadata({title:x.a.dataset.title||"CrowRules Podcasting",artist:x.a.dataset.author||"CrowRules Creator"})}catch{}});navigator.mediaSession.setActionHandler?.("play",()=>x.a.play());navigator.mediaSession.setActionHandler?.("pause",()=>x.a.pause())}}
async function account(){const el=document.querySelector("[data-site-account]");if(!el||!sb)return;const render=s=>{if(s){el.textContent="My Account";el.href="account.html";el.classList.add("account")}else{el.textContent="Sign In";el.href="auth.html";el.classList.remove("account")}};const {data}=await sb.auth.getSession();render(data?.session||null);sb.auth.onAuthStateChange((_event,session)=>render(session));}
window.CrowAudioPlayer={play};
document.addEventListener("DOMContentLoaded",()=>{nav();const x=api();bind();account();try{const saved=JSON.parse(localStorage.getItem("crowrules_audio")||"null");if(saved?.url){x.p.querySelector(".player-title").textContent=saved.title||"CrowRules Podcasting";x.p.querySelector(".player-author").textContent=saved.author||"CrowRules Creator";x.p.querySelector(".player-art").src=saved.artwork||"";x.a.src=saved.url;x.a.dataset.title=saved.title||"";x.a.dataset.author=saved.author||"";}}catch{}});
})();