(()=>{"use strict";
if(window.__CROW_PODCASTING_V15__)return;window.__CROW_PODCASTING_V15__=true;
const BASE="https://crowrulesentertainment-oss.github.io/podcasting/";
function loadV17(){if(window.__CROW_PODCASTING_V17__)return;const s=document.createElement("script");s.src=BASE+"js/universal-v17.js?v=20261005-01";s.defer=true;document.head.appendChild(s);const l=document.createElement("link");l.rel="stylesheet";l.href=BASE+"css/podcasting-v17.css?v=20261005-01";document.head.appendChild(l)}
function loadV16(){if(window.__CROW_PODCASTING_V16__)return;const s=document.createElement("script");s.src=BASE+"js/universal-v16.js?v=20261005-01";s.defer=true;document.head.appendChild(s);const l=document.createElement("link");l.rel="stylesheet";l.href=BASE+"css/podcasting-v16.css?v=20261005-01";document.head.appendChild(l)}
const file=()=>location.pathname.split("/").pop()||"home.html";
const esc=s=>String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
function cleanShell(){document.querySelectorAll("[data-nav]").forEach((el,i)=>{if(i>0)el.remove()});document.querySelectorAll("#crMobileNav,#crConnection,#crRebuildNav,#cr12SiteNav,#cr12SearchButton,#cr12HomeButton").forEach(e=>e.remove());document.body.classList.add("cr15-enhanced");document.documentElement.classList.add("cr15-ready")}
function skip(){if(document.querySelector(".cr15-skip"))return;const a=document.createElement("a");a.className="cr15-skip";a.href="#main,main,[role=main]";a.textContent="Skip to content";document.body.prepend(a)}
function progress(){if(document.querySelector(".cr15-progress"))return;const p=document.createElement("div");p.className="cr15-progress";document.body.appendChild(p);const paint=()=>{const h=document.documentElement.scrollHeight-innerHeight;p.style.width=(h>0?(scrollY/h*100):0)+"%"};addEventListener("scroll",paint,{passive:true});addEventListener("resize",paint,{passive:true});paint()}
function breadcrumb(){if(file()==="index.html"||document.querySelector(".cr15-breadcrumb")||document.body.classList.contains("cr-halloween-theme")&&file()==="launch.html")return;const main=document.querySelector("main");if(!main)return;const b=document.createElement("nav");b.className="cr15-breadcrumb";b.setAttribute("aria-label","Breadcrumb");const label=document.title.replace(/\s*[|—-]\s*CrowRules Podcasting.*$/i,"").trim()||"Podcasting";b.innerHTML='<a href="'+BASE+'home.html">Podcast Home</a><span>›</span><span>'+esc(label)+'</span>';main.before(b)}
function command(){if(document.querySelector(".cr15-command"))return;const o=document.createElement("div");o.className="cr15-command";o.innerHTML='<div class="cr15-command-box" role="dialog" aria-modal="true" aria-label="Podcasting command menu"><input id="cr15CmdInput" placeholder="Jump to a page…" autocomplete="off"><div class="cr15-command-grid"></div></div>';document.body.appendChild(o);const pages=[["home.html","Home"],["discover.html","Discover"],["search.html","Global Search"],["podcasts.html","All Podcasts"],["episodes.html","All Episodes"],["library.html","My Library"],["creator-dashboard.html","Creator Studio"],["creator-profile.html","Creator Profile"],["creator-plans.html","Creator Plans"],["membership.html","Membership"],["notifications.html","Notifications"],["live-chat.html","Community Live Chat"],["account.html","Account"]];const grid=o.querySelector(".cr15-command-grid"),input=o.querySelector("input");const draw=q=>{q=q.toLowerCase();grid.innerHTML=pages.filter(x=>x[1].toLowerCase().includes(q)||x[0].includes(q)).map(x=>'<a class="cr15-command-item" href="'+BASE+x[0]+'"><b>'+esc(x[1])+'</b><br><small>'+esc(x[0])+'</small></a>').join("")||'<div class="cr15-command-item">No matching page.</div>'};draw("");input.oninput=()=>draw(input.value);o.onclick=e=>{if(e.target===o)o.classList.remove("open")};addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();o.classList.toggle("open");if(o.classList.contains("open")){input.value="";draw("");setTimeout(()=>input.focus(),0)}}if(e.key==="Escape")o.classList.remove("open")});}
function repairLinks(){document.querySelectorAll('a[href*="podcast.html?"]').forEach(a=>{const u=new URL(a.href,location.href);const slug=u.searchParams.get("slug");if(slug)a.href=BASE+"podcast.html?slug="+encodeURIComponent(slug)});document.querySelectorAll("img").forEach((img,i)=>{if(!img.hasAttribute("decoding"))img.decoding="async";if(i>2&&!img.hasAttribute("loading"))img.loading="lazy"});document.querySelectorAll("a[target=_blank]").forEach(a=>{const rel=(a.getAttribute("rel")||"").split(/\s+/);if(!rel.includes("noopener"))rel.push("noopener");if(!rel.includes("noreferrer"))rel.push("noreferrer");a.rel=rel.join(" ").trim()})}
function toast(msg){let t=document.querySelector(".cr15-toast");if(!t){t=document.createElement("div");t.className="cr15-toast";document.body.appendChild(t)}t.textContent=msg;t.hidden=false;clearTimeout(window.__CR15TOAST);window.__CR15TOAST=setTimeout(()=>t.hidden=true,2600)}
function health(){window.addEventListener("error",e=>{if(e?.message)console.warn("CrowRules Podcasting V15:",e.message)});window.addEventListener("unhandledrejection",e=>console.warn("CrowRules Podcasting V15 promise:",e.reason||e))}
function boot(){loadV16();loadV17();cleanShell();skip();progress();breadcrumb();command();repairLinks();health();window.CROW_PODCASTING_V15={version:"15.0.0",toast,openCommand:()=>document.querySelector(".cr15-command")?.classList.add("open")};window.dispatchEvent(new CustomEvent("crow:v15:ready"))}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else boot();
})();