(()=>{"use strict";
const SUPABASE_URL="https://cevylpnoexugwgygvtgu.supabase.co",SUPABASE_KEY="sb_publishable_AdfM5y6RqvF3tbvEVzDZSg_JuGTQLD-";
let sb=null,authBound=false,experienceBound=false;
const wait=ms=>new Promise(r=>setTimeout(r,ms));
function createSupabaseClient(){if(window.CROW_SUPABASE?.auth)return window.CROW_SUPABASE;if(!window.supabase?.createClient)return null;try{const c=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,flowType:"pkce"}});window.CROW_SUPABASE=c;return c}catch(e){return null}}
async function getSupabase(){if(sb)return sb;for(let i=0;i<40;i++){sb=createSupabaseClient();if(sb)return sb;await wait(250)}return null}
window.CrowRulesSite=Object.freeze({supabaseUrl:SUPABASE_URL,product:"CrowRules Podcasting",version:"2.2",getClient:()=>getSupabase(),getSession:async()=>{const c=await getSupabase();return c?(await c.auth.getSession()).data.session:null}});
const page=(location.pathname.split("/").pop()||"home.html").toLowerCase(),nav=[["home.html","Home"],["discover.html","Discover"],["rankings.html","Rankings"],["library.html","Library"],["creator-studio.html","Studio"],["membership.html","Membership"],["community.html","Community"],["launch.html","Launch"]];
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",""":"&quot;","'":"&#039;"}[c]));
function shell(){if(document.querySelector(".sitewide-header"))return;document.querySelector(".site-header")?.remove();const h=document.createElement("header");h.className="sitewide-header";h.innerHTML='<a class="sitewide-brand" href="home.html" aria-label="CrowRules Podcasting home"><span class="sitewide-mark">C</span><span><b>CrowRules</b><small>Podcasting / Cyberspace</small></span></a><nav class="sitewide-nav" aria-label="Primary">'+nav.map(([u,l])=>'<a href="'+u+'" class="'+(page===u?"active":"")+'">'+l+"</a>").join("")+'<a class="sitewide-account" data-site-account href="auth.html">Sign In</a></nav><button class="sitewide-menu" aria-label="Open menu" aria-expanded="false">☰</button><nav class="sitewide-mobile" aria-label="Mobile">'+nav.map(([u,l])=>'<a href="'+u+'">'+l+"</a>").join("")+'<a class="sitewide-account" data-site-account href="auth.html">Sign In</a></nav>';document.body.prepend(h);const menu=h.querySelector(".sitewide-menu"),mobile=h.querySelector(".sitewide-mobile");menu.onclick=()=>{const open=mobile.classList.toggle("open");menu.setAttribute("aria-expanded",String(open))};mobile.addEventListener("click",e=>{if(e.target.matches("a"))mobile.classList.remove("open")});const f=document.createElement("footer");f.className="sitewide-footer";f.innerHTML='CROWRULES PODCASTING • CYBERSPACE AUDIO NETWORK • <a href="https://crowrulesentertainment-oss.github.io/crowrulesentertainment/">CrowRules Entertainment</a><span class="sitewide-status" aria-live="polite"> • SYSTEM ONLINE</span>';document.body.append(f);player()}
function player(){if(document.querySelector(".sitewide-player"))return;const p=document.createElement("div");p.className="sitewide-player";p.innerHTML='<div class="player-info"><div class="player-title" id="playerTitle">Nothing playing</div><div class="player-sub" id="playerSub">CrowRules cyberspace audio link offline</div><div class="player-progress"><span id="playerProgress"></span></div></div><div class="player-controls"><button id="playerPlay" class="primary" aria-label="Play or pause">▶</button><button id="playerMute" aria-label="Mute">🔊</button><button id="playerClose" aria-label="Close player">×</button></div>';document.body.append(p);const audio=document.createElement("audio");audio.id="crAudio";audio.preload="metadata";document.body.append(audio);let saved=null;try{saved=JSON.parse(localStorage.getItem("crowrules_audio")||"null")}catch{}const title=document.getElementById("playerTitle"),sub=document.getElementById("playerSub"),play=document.getElementById("playerPlay"),mute=document.getElementById("playerMute"),close=document.getElementById("playerClose"),progress=document.getElementById("playerProgress");if(saved?.src){audio.src=saved.src;title.textContent=saved.title||"CrowRules Podcast";sub.textContent=saved.sub||"Ready to resume";audio.currentTime=Number(saved.time)||0}play.onclick=()=>audio.paused?audio.play().catch(()=>{}):audio.pause();mute.onclick=()=>{audio.muted=!audio.muted;mute.textContent=audio.muted?"🔇":"🔊"};close.onclick=()=>{audio.pause();audio.removeAttribute("src");localStorage.removeItem("crowrules_audio");title.textContent="Nothing playing";sub.textContent="CrowRules cyberspace audio link offline";progress.style.width="0%"};audio.onplay=()=>play.textContent="Ⅱ";audio.onpause=()=>play.textContent="▶";audio.ontimeupdate=()=>{if(audio.duration){progress.style.width=audio.currentTime/audio.duration*100+"%";if(audio.currentTime>0&&audio.currentTime%5<.25){localStorage.setItem("crowrules_audio",JSON.stringify({src:audio.src,title:title.textContent,sub:sub.textContent,time:audio.currentTime}));saveExperienceProgress()}}};audio.onended=()=>{play.textContent="▶";progress.style.width="0%";saveExperienceProgress(true);const m=window.CrowRulesNowPlaying;if(m?.episodeId)analyticsEvent("complete",m,audio.duration||m.durationSeconds||0,audio.duration||m.durationSeconds||0)};window.CrowRulesPlay=(src,name,detail,meta={})=>{if(!src)return;window.CrowRulesNowPlaying={...meta,src,name,detail};audio.src=src;title.textContent=name||"CrowRules Podcast";sub.textContent=detail||"Now playing";localStorage.setItem("crowrules_audio",JSON.stringify({src,title:name||"CrowRules Podcast",sub:detail||"Now playing",time:0}));audio.play().catch(()=>{});recordExperiencePlay(meta);};window.CrowRulesAudio=audio}
async function currentSession(){const c=await getSupabase();return c?(await c.auth.getSession()).data.session:null}
async function saveExperienceProgress(completed=false){const m=window.CrowRulesNowPlaying;if(!m?.episodeId)return;const s=await currentSession();if(!s||!window.CrowRulesAudio)return;const a=window.CrowRulesAudio,d=Math.round(a.duration||m.durationSeconds||0),pos=Math.round(a.currentTime||0);try{await sb.from("podcast_user_episode_progress").upsert({user_id:s.user.id,episode_id:m.episodeId,position_seconds:pos,duration_seconds:d,completed:completed||!!(d&&pos>=Math.max(0,d-5)),updated_at:new Date().toISOString()},{onConflict:"user_id,episode_id"});document.dispatchEvent(new CustomEvent("crowrules:experience"))}catch(e){console.warn("[CrowRules Experience] progress",e)}}
async function analyticsEvent(type,meta={},position=0,duration=0){if(!meta?.episodeId)return;const s=await currentSession();if(!s)return;try{await sb.from("podcast_analytics_events").insert({podcast_id:meta.podcastId||null,episode_id:meta.episodeId,user_id:s.user.id,event_type:type,position_seconds:Math.round(position||0),duration_seconds:Math.round(duration||0)});}catch(e){console.warn("[CrowRules Analytics] event",e)}}
async function recordExperiencePlay(meta={}){if(!meta.episodeId)return;const s=await currentSession();if(!s)return;try{await sb.from("podcast_user_recently_played").upsert({user_id:s.user.id,episode_id:meta.episodeId,last_played_at:new Date().toISOString(),play_position_seconds:0},{onConflict:"user_id,episode_id"});if(meta.queuePosition!=null)await sb.from("podcast_user_queue").update({position:meta.queuePosition}).eq("user_id",s.user.id).eq("episode_id",meta.episodeId);await analyticsEvent("play",meta,0,meta.durationSeconds||0)}catch(e){console.warn("[CrowRules Experience] recent",e)}}
async function libraryAction(podcastId,itemType,active){const s=await currentSession();if(!s){toast("Sign in to use this feature.");return false}if(active){const r=await sb.from("podcast_user_library").delete().eq("user_id",s.user.id).eq("podcast_id",podcastId).eq("item_type",itemType);if(r.error)throw r.error}else{const r=await sb.from("podcast_user_library").upsert({user_id:s.user.id,podcast_id:podcastId,item_type:itemType},{onConflict:"user_id,podcast_id,item_type"});if(r.error)throw r.error}document.dispatchEvent(new CustomEvent("crowrules:experience"));return !active}
async function queueAction(episodeId,remove=false){const s=await currentSession();if(!s){toast("Sign in to build your queue.");return false}if(remove){const r=await sb.from("podcast_user_queue").delete().eq("user_id",s.user.id).eq("episode_id",episodeId);if(r.error)throw r.error}else{const q=await sb.from("podcast_user_queue").select("position").eq("user_id",s.user.id).order("position",{ascending:false}).limit(1).maybeSingle();const position=Number(q.data?.position||0)+1;const r=await sb.from("podcast_user_queue").upsert({user_id:s.user.id,episode_id:episodeId,position},{onConflict:"user_id,episode_id"});if(r.error)throw r.error}document.dispatchEvent(new CustomEvent("crowrules:experience"));return true}
window.CrowRulesExperience={follow:(id,a)=>libraryAction(id,"follow",a),favorite:(id,a)=>libraryAction(id,"favorite",a),queue:(id,r)=>queueAction(id,r),progress:saveExperienceProgress,sync:()=>document.dispatchEvent(new CustomEvent("crowrules:experience"))};
function toast(m){let t=document.getElementById("toast");if(!t){t=document.createElement("div");t.id="toast";t.className="toast";document.body.append(t)}t.textContent=m;t.classList.add("show");clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove("show"),3200)}
window.CrowRulesToast=toast;
async function account(){const c=await getSupabase();if(!c)return;try{const {data}=await c.auth.getSession(),s=data?.session||null;document.querySelectorAll("[data-site-account]").forEach(a=>{a.textContent=s?"My Account":"Sign In";a.href=s?"account.html":"auth.html"});if(!authBound){authBound=true;c.auth.onAuthStateChange((_e,ns)=>{document.querySelectorAll("[data-site-account]").forEach(a=>{a.textContent=ns?"My Account":"Sign In";a.href=ns?"account.html":"auth.html"});document.dispatchEvent(new CustomEvent("crowrules:session",{detail:ns}))})}}catch(e){console.warn("[CrowRules Sitewide] auth",e)}}
function installGlobalState(client){window.CrowRulesState=window.CrowRulesState||{session:null,online:true,page:location.pathname};const state=window.CrowRulesState;state.supabase=client;client.auth.getSession().then(({data})=>{state.session=data?.session||null;document.dispatchEvent(new CustomEvent("crowrules:session",{detail:state.session}))}).catch(()=>{state.online=false});if(!authBound){authBound=true;client.auth.onAuthStateChange((_e,s)=>{state.session=s||null;state.online=true;document.dispatchEvent(new CustomEvent("crowrules:session",{detail:s||null}))})}}
function setStatus(t){document.querySelectorAll(".sitewide-status").forEach(el=>el.textContent=" • "+t)}
function connectionStatus(){setStatus(navigator.onLine?"SYSTEM ONLINE":"OFFLINE • RECONNECTING");document.documentElement.dataset.crowOnline=navigator.onLine?"true":"false"}
function savePageState(){try{sessionStorage.setItem("crowrules_last_page",location.pathname+location.search)}catch{}}
function enhanceLinks(){document.querySelectorAll("a[href]").forEach(a=>{if(a.dataset.crEnhanced)return;a.dataset.crEnhanced="1";const h=a.getAttribute("href")||"";if(h.startsWith("#")||h.startsWith("http")||h.startsWith("mailto:")||h.startsWith("javascript:"))return;a.addEventListener("click",savePageState)})}
function hero3d(){const root=document.querySelector(".hero");if(!root||matchMedia("(prefers-reduced-motion: reduce)").matches)return;let raf=0;document.addEventListener("mousemove",e=>{cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>{const x=(innerWidth/2-e.clientX)/innerWidth,y=(innerHeight/2-e.clientY)/innerHeight;root.style.transform="perspective(1200px) rotateY("+(x*2.2)+"deg) rotateX("+(y*-1.7)+"deg)"})})}
document.addEventListener("DOMContentLoaded",()=>{shell();account();getSupabase().then(c=>{if(c)installGlobalState(c);connectionStatus()}).catch(()=>setStatus("OFFLINE • RECONNECTING"));enhanceLinks();hero3d()});
})();