(()=>{"use strict";
if(window.__CROW_SITEWIDE_V13__)return;window.__CROW_SITEWIDE_V13__=true;
const BASE="https://crowrulesentertainment-oss.github.io/podcasting/";
const page=(location.pathname.split("/").pop()||"home.html").toLowerCase();
const esc=s=>String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]||c));
function clean(){document.querySelectorAll("[data-nav],#crMobileNav,#crConnection,#crRebuildNav,#cr12SiteNav,#cr12SearchButton,#cr12HomeButton,.cr-nav,.cr13-nav,.cr13-player,.cr13-search-overlay,.cr13-notification-panel").forEach(e=>e.remove());document.body.classList.add("cr-app")}
function group(label,links){return '<div class="cr13-group"><button class="cr13-trigger" type="button" aria-haspopup="true" aria-expanded="false">'+esc(label)+'⌄</button><div class="cr13-menu"><small>CROWRULES PODCASTING</small>'+links.map(x=>'<a href="'+BASE+x[0]+'">'+esc(x[1])+'</a>').join("")+'</div></div>'}
function nav(){const n=document.createElement("header");n.className="cr13-nav";n.innerHTML='<a class="cr13-brand" href="'+BASE+'home.html"><b>CROWRULES</b><span>PODCASTING</span></a><nav class="cr13-links" aria-label="Podcasting navigation"><a class="cr13-link '+(page==="home.html"?"active":"")+'" href="'+BASE+'home.html">HOME</a>'+group("DISCOVER",[["discover.html","Discover"],["search.html","Global Search"],["podcasts.html","All Podcasts"],["episodes.html","All Episodes"],["intelligence.html","Intelligence Layer"],["presence.html","Live Network"]])+group("LIBRARY",[["library.html","My Library"],["library.html#continue","Continue Listening"],["notifications.html","Notifications"]])+group("CREATORS",[["create-podcast.html","Create Podcast"],["creator-dashboard.html","Creator Studio"],["creator-profile.html","Creator Profile"],["creator-intelligence.html","Creator Intelligence"]])+group("COMMUNITY",[["live-chat.html","Live Chat"],["member-listener.html","Listener Profile"],["members-podcaster.html","Podcaster Community"]])+group("ACCOUNT",[["account.html","Account"],["membership.html","Membership"],["verify.html","Verify Account"]])+'</nav><div class="cr13-tools"><button id="cr13Search" title="Search" aria-label="Global search">⌕</button><button id="cr13Notify" title="Notifications" aria-label="Notifications">♢</button><a href="'+BASE+'account.html" title="Account">◎</a><button class="cr13-mobile" id="cr13Mobile" aria-label="Open menu" aria-expanded="false">☰</button></div>';document.body.prepend(n);
n.querySelectorAll(".cr13-group").forEach(g=>{const b=g.querySelector("button");b.onclick=e=>{e.stopPropagation();n.querySelectorAll(".cr13-group").forEach(x=>{if(x!==g)x.classList.remove("open")});g.classList.toggle("open");b.setAttribute("aria-expanded",g.classList.contains("open"))}});
document.addEventListener("click",()=>n.querySelectorAll(".cr13-group").forEach(g=>g.classList.remove("open")),{passive:true});
n.querySelector("#cr13Search").onclick=()=>window.CROW_V13_SEARCH?.open();
n.querySelector("#cr13Notify").onclick=()=>window.CROW_V13_NOTIFY?.toggle();
const m=document.createElement("div");m.className="cr13-mobile-panel";m.hidden=true;m.innerHTML=["home.html|HOME","discover.html|DISCOVER","search.html|GLOBAL SEARCH","podcasts.html|PODCASTS","episodes.html|EPISODES","library.html|LIBRARY","creator-dashboard.html|CREATOR STUDIO","account.html|ACCOUNT","notifications.html|NOTIFICATIONS"].map(x=>{const [h,l]=x.split("|");return '<a href="'+BASE+h+'">'+l+'</a>'}).join("");document.body.appendChild(m);n.querySelector("#cr13Mobile").onclick=e=>{e.stopPropagation();m.hidden=!m.hidden}}
function status(){let s=document.querySelector(".cr13-status");if(!s){s=document.createElement("div");s.className="cr13-status";s.textContent="SUPABASE • CONNECTING";document.body.appendChild(s)}window.addEventListener("crow:connection",e=>{s.textContent=e.detail?.ok?"SUPABASE • ONLINE":"SUPABASE • ERROR";s.classList.toggle("bad",!e.detail?.ok)});if(window.CROW_SUPABASE_CONNECTION==="connected")s.textContent="SUPABASE • ONLINE"}
async function memberContext(){const sb=window.CROW_SUPABASE,u=window.__CROW_USER;if(!sb)return;document.documentElement.dataset.crowAuth=u?"signed-in":"signed-out";if(!u){window.CROW_MEMBER_CONTEXT={user:null,member:null};return}try{const m=await sb.from("members").select("display_name,username,membership_type,role,status").eq("user_id",u.id).maybeSingle();window.CROW_MEMBER_CONTEXT={user:u,member:m.data||null}}catch(e){console.warn("CrowRules member context:",e.message||e)}}
function player(){const p=document.createElement("section");p.className="cr13-player";p.setAttribute("aria-label","CrowRules universal podcast player");p.innerHTML='<div class="cr13-player-art">🎙</div><div class="cr13-player-meta"><b id="cr13Track">Nothing playing</b><span id="cr13Creator">Choose a podcast or episode</span></div><button id="cr13Prev" title="Previous">↶</button><button id="cr13Play" class="primary" title="Play or pause">▶</button><button id="cr13Next" title="Next">↷</button><div class="cr13-progress"><input id="cr13Seek" type="range" min="0" max="100" value="0" step=".1" aria-label="Playback position"><div><span id="cr13Current">0:00</span><span id="cr13Duration">0:00</span></div></div><button id="cr13Speed" title="Playback speed">1×</button><button id="cr13Close" title="Close player">×</button><audio id="cr13Audio" preload="metadata"></audio>';document.body.appendChild(p);
const audio=p.querySelector("#cr13Audio"),play=p.querySelector("#cr13Play"),seek=p.querySelector("#cr13Seek"),track=p.querySelector("#cr13Track"),creator=p.querySelector("#cr13Creator"),cur=p.querySelector("#cr13Current"),dur=p.querySelector("#cr13Duration"),speed=p.querySelector("#cr13Speed");
const fmt=s=>{s=Math.max(0,Math.floor(Number(s)||0));return Math.floor(s/60)+":"+String(s%60).padStart(2,"0")};let state={};
try{state=JSON.parse(localStorage.getItem("crowrules_universal_player_v13")||"{}")}catch(_){}
function save(){try{localStorage.setItem("crowrules_universal_player_v13",JSON.stringify({id:state.id,title:state.title,creator:state.creator,url:state.url,position:audio.currentTime,speed:audio.playbackRate}))}catch(_){}}
function load(s,autoplay){if(!s?.url)return;state=s;track.textContent=s.title||"Untitled episode";creator.textContent=s.creator||"CrowRules Podcasting";audio.src=s.url;audio.playbackRate=Number(s.speed)||1;audio.currentTime=Number(s.position)||0;p.classList.add("active");window.CROW_PLAYER_STATE=state;if(autoplay)audio.play().catch(()=>{});save();window.dispatchEvent(new CustomEvent("crow:player",{detail:state}))}
window.CROW_PLAYER={load,play:()=>audio.play().catch(()=>{}),pause:()=>audio.pause(),state:()=>({...state,position:audio.currentTime})};
play.onclick=()=>audio.paused?audio.play().catch(()=>{}):audio.pause();
audio.onplay=()=>{play.textContent="Ⅱ";p.classList.add("playing")};audio.onpause=()=>{play.textContent="▶";p.classList.remove("playing");save()};
audio.ontimeupdate=()=>{seek.value=audio.duration?(audio.currentTime/audio.duration*100):0;cur.textContent=fmt(audio.currentTime);save();progress()};
audio.onloadedmetadata=()=>{dur.textContent=fmt(audio.duration);if(state.position)audio.currentTime=Math.min(state.position||0,audio.duration||state.position);};
seek.oninput=()=>{if(audio.duration)audio.currentTime=audio.duration*(Number(seek.value)/100);};
speed.onclick=()=>{const v=audio.playbackRate>=2?1:Number((audio.playbackRate+.25).toFixed(2));audio.playbackRate=v;speed.textContent=v+"×";save()};
p.querySelector("#cr13Close").onclick=()=>{audio.pause();p.classList.remove("active");try{localStorage.removeItem("crowrules_universal_player_v13")}catch(_){}};
p.querySelector("#cr13Prev").onclick=()=>window.dispatchEvent(new Event("crow:player-prev"));p.querySelector("#cr13Next").onclick=()=>window.dispatchEvent(new Event("crow:player-next"));
try{if(state.url){track.textContent=state.title||"Resume listening";creator.textContent=state.creator||"CrowRules Podcasting";p.classList.add("active");audio.src=state.url;audio.playbackRate=Number(state.speed)||1}}catch(_){}
async function progress(){const sb=window.CROW_SUPABASE,u=window.__CROW_USER;if(!sb||!u||!state.id||!Number.isFinite(audio.currentTime))return;clearTimeout(window.__CRPROG);window.__CRPROG=setTimeout(async()=>{const payload={user_id:u.id,episode_id:state.id,position_seconds:Math.floor(audio.currentTime),duration_seconds:Math.floor(audio.duration||0),updated_at:new Date().toISOString()};for(const table of ["podcast_listening_history","podcast_watch_history","watch_history"]){try{const r=await sb.from(table).upsert(payload,{onConflict:"user_id,episode_id"});if(!r.error)break}catch(_){} }},1200)}
}
function searchOverlay(){const o=document.createElement("div");o.className="cr13-search-overlay";o.hidden=true;o.innerHTML='<div class="cr13-search-box"><button class="cr13-search-close" aria-label="Close">×</button><div class="cr13-search-kicker">CROWRULES PODCASTING INTELLIGENCE</div><h2>Search the network</h2><input id="cr13SearchInput" autocomplete="off" placeholder="Podcasts, episodes, creators…" autofocus><div id="cr13SearchResults"><span>Start typing to search.</span></div></div>';document.body.appendChild(o);const input=o.querySelector("input"),results=o.querySelector("#cr13SearchResults");async function run(){const q=input.value.trim();if(q.length<2){results.innerHTML="<span>Start typing to search.</span>";return}results.innerHTML="<span>Searching the CrowRules network…</span>";const sb=window.CROW_SUPABASE;if(!sb){results.innerHTML="<span>Supabase is not connected.</span>";return}const sets=[];for(const table of ["podcasts","episodes","creators"]){try{const r=await sb.from(table).select("*").or("title.ilike.%"+q+"%,name.ilike.%"+q+"%,description.ilike.%"+q+"%").limit(6);if(!r.error)(r.data||[]).forEach(x=>sets.push({...x,__table:table}))}catch(_){}}
if(!sets.length){results.innerHTML='<div class="cr13-empty">No matches yet.<br><a href="'+BASE+'search.html?q='+encodeURIComponent(q)+'">Open full search</a></div>';return}
results.innerHTML=sets.map(x=>{const title=x.title||x.name||x.full_name||"Untitled";const id=x.id||x.slug||"";return '<button class="cr13-result" data-id="'+esc(id)+'" data-table="'+x.__table+'"><b>'+esc(title)+'</b><small>'+esc(x.__table.replace("podcasts","Podcast").replace("episodes","Episode").replace("creators","Creator"))+'</small></button>'}).join("");results.querySelectorAll(".cr13-result").forEach(b=>b.onclick=()=>{const x=sets.find(z=>String(z.id||z.slug||"")===b.dataset.id);if(x?.__table==="episodes"){const url=x.audio_url||x.media_url||x.audio||x.url;if(url)window.CROW_PLAYER?.load({id:x.id,title:x.title||x.name,creator:x.creator_name||x.author_name||"CrowRules Podcasting",url},true)}else location.href=BASE+(x.__table==="podcasts"?"podcast.html?slug=":"search.html?q=")+encodeURIComponent(x.slug||x.title||x.name||"")});}
o.querySelector(".cr13-search-close").onclick=()=>o.hidden=true;o.onclick=e=>{if(e.target===o)o.hidden=true};input.oninput=()=>{clearTimeout(window.__CRSEARCH);window.__CRSEARCH=setTimeout(run,250)};window.CROW_V13_SEARCH={open:()=>{o.hidden=false;setTimeout(()=>input.focus(),30)},close:()=>o.hidden=true}}
function notifications(){const panel=document.createElement("aside");panel.className="cr13-notification-panel";panel.hidden=true;panel.innerHTML='<div><b>Notifications</b><button id="cr13NotifClose">×</button></div><section id="cr13NotifList"><span>Loading…</span></section>';document.body.appendChild(panel);async function load(){const sb=window.CROW_SUPABASE,u=window.__CROW_USER;const box=panel.querySelector("#cr13NotifList");if(!u){box.innerHTML='<span>Sign in to see your notifications.</span>';return}try{const r=await sb.from("podcast_notifications").select("*").eq("user_id",u.id).order("created_at",{ascending:false}).limit(20);if(r.error)throw r.error;box.innerHTML=(r.data||[]).map(x=>'<article><b>'+esc(x.title||"CrowRules")+'</b><p>'+esc(x.message||x.body||"New activity")+'</p></article>').join("")||"<span>No new notifications.</span>"}catch(e){box.innerHTML="<span>Notifications are temporarily unavailable.</span>"}}panel.querySelector("#cr13NotifClose").onclick=()=>panel.hidden=true;window.CROW_V13_NOTIFY={toggle:()=>{panel.hidden=!panel.hidden;if(!panel.hidden)load()},load};}
function realtime(){const sb=window.CROW_SUPABASE;if(!sb||window.CROW_SITE_REALTIME)return;window.CROW_SITE_REALTIME=true;try{const ch=sb.channel("crowrules-podcasting-v13-intelligence").on("postgres_changes",{event:"*",schema:"public",table:"podcast_notifications"},()=>{window.dispatchEvent(new Event("crow:notifications-changed"));window.CROW_V13_NOTIFY?.load()}).on("postgres_changes",{event:"*",schema:"public",table:"podcasts"},()=>window.dispatchEvent(new Event("crow:catalog-changed"))).on("postgres_changes",{event:"*",schema:"public",table:"episodes"},()=>window.dispatchEvent(new Event("crow:catalog-changed"))).subscribe();window.CROW_SITE_CHANNEL=ch}catch(e){console.warn("CrowRules realtime:",e)}}
function boot(){clean();nav();status();player();searchOverlay();notifications();memberContext();realtime();window.addEventListener("crow:auth",memberContext);window.addEventListener("crow:ready",()=>{memberContext();realtime()})}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else boot();
})();