import {getSupabase} from "./supabase.js";
const db=await getSupabase();const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));
async function user(){if(!db)return null;const {data}=await db.auth.getUser();return data?.user||null}
async function following(){const root=document.querySelector("#followingPage");if(!root)return;const u=await user();if(!u){root.innerHTML='<div class="panel empty"><h2>Sign in to see your following feed.</h2><a class="btn primary" href="account.html">Sign in</a></div>';return}
const {data,error}=await db.from("podcast_follows").select("podcast_id,created_at").eq("user_id",u.id).order("created_at",{ascending:false});if(error){root.innerHTML='<div class="panel empty"><p>'+esc(error.message)+'</p></div>';return}
const ids=(data||[]).map(x=>x.podcast_id);if(!ids.length){root.innerHTML='<div class="panel empty"><h2>Nothing here yet.</h2><p>Follow a podcast to build your feed.</p><a class="btn primary" href="discover.html">Discover podcasts</a></div>';return}
const {data:shows}=await db.from("podcasts").select("id,title,slug,description,artwork_url").in("id",ids);root.innerHTML='<div class="card-grid">'+(shows||[]).map(s=>'<article class="show-card"><a href="podcast.html?show='+encodeURIComponent(s.slug||s.id)+'"><img src="'+esc(s.artwork_url||"")+'" alt="" loading="lazy"><div class="card-copy"><span class="badge">FOLLOWING</span><h3>'+esc(s.title)+'</h3><p>'+esc(s.description||"")+'</p></div></a></article>').join("")+'</div>'}
async function playlists(){const root=document.querySelector("#playlistPage");if(!root)return;const u=await user();if(!u){root.innerHTML='<div class="panel empty"><h2>Sign in to create playlists.</h2><a class="btn primary" href="account.html">Sign in</a></div>';return}
let rows=[],remote=true;try{const q=await db.from("podcast_playlists").select("id,name,description,is_public,created_at").eq("user_id",u.id).order("created_at",{ascending:false});if(q.error)throw q.error;rows=q.data||[]}catch{remote=false;rows=JSON.parse(localStorage.getItem("cr_playlists")||"[]")}
root.innerHTML='<div class="panel"><form class="form" id="playlistForm"><label>Playlist name<input name="name" required placeholder="My Favorites"></label><label>Description<textarea name="description" rows="2"></textarea></label><button class="btn primary">Create playlist</button></form></div><section class="section"><div class="card-grid" id="playlistCards">'+(rows.length?rows.map(p=>'<div class="panel"><p class="eyebrow">PLAYLIST</p><h2>'+esc(p.name)+'</h2><p>'+esc(p.description||"Personal listening collection.")+'</p><span class="chip">'+(p.is_public?"PUBLIC":"PRIVATE")+'</span></div>').join(""):'<div class="panel empty"><p>Create your first playlist.</p></div>')+'</div></section>';
document.querySelector("#playlistForm").onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const item={name:fd.get("name"),description:fd.get("description"),is_public:false};if(remote){const q=await db.from("podcast_playlists").insert({...item,user_id:u.id}).select().single();if(q.error){alert(q.error.message);return}}else{rows.unshift({...item,id:crypto.randomUUID()});localStorage.setItem("cr_playlists",JSON.stringify(rows))}playlists()}}
async function notifications(){const root=document.querySelector("#notificationPage");if(!root)return;const u=await user();if(!u){root.innerHTML='<div class="panel empty"><h2>Sign in to view notifications.</h2><a class="btn primary" href="account.html">Sign in</a></div>';return}
try{const q=await db.from("podcast_creator_notifications").select("title,message,created_at,read_at").eq("user_id",u.id).order("created_at",{ascending:false}).limit(50);if(q.error)throw q.error;root.innerHTML='<div class="table panel">'+((q.data||[]).map(n=>'<div><b>'+esc(n.title)+'</b><span>'+esc(n.message||"")+' • '+new Date(n.created_at).toLocaleString()+'</span></div>').join("")||'<div><b>No new notifications</b><span>Your signal feed is clear.</span></div>')+'</div>'}catch{root.innerHTML='<div class="panel empty"><p>Your notification center is ready; creator notification data is not available for this account yet.</p></div>'}}
following();playlists();notifications();