import {getSupabase} from "./supabase.js";
const db=await getSupabase(),root=document.querySelector("#submissionPage");
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));
const PLATFORMS=[
 {key:"apple_podcasts",name:"Apple Podcasts",url:"https://podcastersconnect.apple.com/",req:["RSS feed","Podcast title","Author / host","Contact email","Category","Artwork","Published episode with public audio"]},
 {key:"spotify",name:"Spotify for Creators",url:"https://creators.spotify.com/",req:["RSS feed","Podcast identity","Artwork","Published episode with public audio"]},
 {key:"youtube_music",name:"YouTube / YouTube Music",url:"https://studio.youtube.com/",req:["RSS feed or supported import workflow","Podcast identity","Artwork","Public audio episodes"]},
 {key:"amazon_music",name:"Amazon Music",url:"https://podcasters.amazon.com/",req:["RSS feed","Podcast identity","Public audio episodes"]},
 {key:"pocket_casts",name:"Pocket Casts",url:"https://pocketcasts.com/submit/",req:["Public RSS feed","Valid public audio enclosures"]},
 {key:"podchaser",name:"Podchaser",url:"https://www.podchaser.com/add",req:["Public RSS feed","Podcast identity","Published episodes"]}
];
async function load(){if(!db){root.innerHTML='<div class="panel empty">Supabase is not configured.</div>';return}const {data:{user}}=await db.auth.getUser();if(!user){root.innerHTML='<div class="panel empty"><h2>Sign in to manage distribution.</h2><a class="btn primary" href="account.html">Open account</a></div>';return}
const {data:podcasts,error}=await db.from("podcasts").select("id,title,slug,description,artwork_url,status,category,author_name,author_email,language,website_url").order("title");if(error){root.innerHTML='<div class="panel empty">'+esc(error.message)+'</div>';return}if(!podcasts?.length){root.innerHTML='<div class="panel empty"><h2>No podcasts found.</h2><a class="btn primary" href="create-podcast.html">Create podcast</a></div>';return}
const {data:rows}=await db.from("podcast_distribution_status").select("podcast_id,platform,status,submission_url,external_url,notes,updated_at").in("podcast_id",podcasts.map(p=>p.id));
const map=new Map((rows||[]).map(x=>[x.podcast_id+"|"+x.platform,x]));
root.innerHTML=podcasts.map(p=>{const feed="https://cevylpnoexugwgygvtgu.supabase.co/functions/v1/podcast-rss?slug="+encodeURIComponent(p.slug);return '<section class="panel" style="margin-bottom:22px"><div class="section-head"><div><p class="eyebrow">PODCAST</p><h2>'+esc(p.title)+'</h2><p class="muted">'+esc(p.author_name||"Author not set")+' • '+esc(p.language||"en-us")+'</p></div><a class="btn" href="validator.html">Validate RSS</a></div><div class="feed-box">'+esc(feed)+'</div><div class="copy-actions"><button class="btn" data-copy="'+esc(feed)+'">Copy RSS feed</button><a class="btn" target="_blank" rel="noopener" href="'+esc(feed)+'">Open feed</a></div><div class="platform-grid" style="margin-top:18px">'+PLATFORMS.map(x=>{const s=map.get(p.id+"|"+x.key)||{status:"not_submitted",submission_url:x.url,external_url:"",notes:""};return '<article class="panel platform-card"><p class="eyebrow">'+esc(x.name)+'</p><h3>'+({not_submitted:"Not submitted",preparing:"Preparing",submitted:"Submitted",listed:"Listed",needs_attention:"Needs attention",rejected:"Rejected"}[s.status]||s.status)+'</h3><select class="status-select" data-id="'+p.id+'" data-platform="'+x.key+'">'+["not_submitted","preparing","submitted","listed","needs_attention","rejected"].map(v=>'<option value="'+v+'" '+(s.status===v?"selected":"")+'>'+v.replaceAll("_"," ")+'</option>').join("")+'</select><ul class="checklist">'+x.req.map(q=>'<li>✓ '+esc(q)+'</li>').join("")+'</ul><p class="small-note">Submission / directory page</p><a class="btn" target="_blank" rel="noopener" href="'+esc(s.submission_url||x.url)+'">Open platform</a><label style="display:block;margin-top:12px">Listing URL (optional)<input data-ext="'+p.id+'" data-platform="'+x.key+'" value="'+esc(s.external_url||"")+'" placeholder="https://..."></label><label style="display:block;margin-top:12px">Notes<textarea data-note="'+p.id+'" data-platform="'+x.key+'" rows="3" placeholder="Submission notes">'+esc(s.notes||"")+'</textarea></label></article>'}).join("")+'</div></section>'}).join("");
document.querySelectorAll("[data-copy]").forEach(b=>b.onclick=async()=>{await navigator.clipboard.writeText(b.dataset.copy);b.textContent="Copied";setTimeout(()=>b.textContent="Copy RSS feed",1400)});
document.querySelectorAll("[data-id]").forEach(s=>s.onchange=()=>save(s));
document.querySelectorAll("[data-ext],[data-note]").forEach(i=>i.addEventListener("change",()=>save(i)));
async function save(node){const id=node.dataset.id||node.dataset.ext||node.dataset.note,platform=node.dataset.platform;const sel=document.querySelector('[data-id="'+id+'"][data-platform="'+platform+'"]');const ext=document.querySelector('[data-ext="'+id+'"][data-platform="'+platform+'"]')?.value||"";const note=document.querySelector('[data-note="'+id+'"][data-platform="'+platform+'"]')?.value||"";const platformInfo=PLATFORMS.find(x=>x.key===platform);const {error}=await db.from("podcast_distribution_status").upsert({podcast_id:id,platform,status:sel?.value||"not_submitted",submission_url:platformInfo?.url||"",external_url:ext,notes:note,updated_by:user.id,updated_at:new Date().toISOString()},{onConflict:"podcast_id,platform"});if(error)alert(error.message)}
}load();