import {getSupabase} from "./supabase.js";
const db=await getSupabase(),root=document.querySelector("#trustCenter"),MOD="https://cevylpnoexugwgygvtgu.supabase.co/functions/v1/podcast-live-moderation";let user,podcastId,roles=[],invites=[],schedules=[],reports=[],strikes=[],rules=[],trust=[],actions=[];
const esc=s=>String(s??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;"),fmt=n=>Number(n||0).toLocaleString(),ago=t=>{const s=Math.max(0,Math.floor((Date.now()-new Date(t))/1000));return s<60?s+"s ago":Math.floor(s/60)+"m ago"};
async function api(action,extra={}){const s=(await db.auth.getSession()).data.session;if(!s)return null;const r=await fetch(MOD,{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+s.access_token},body:JSON.stringify({action,target_podcast_id:podcastId,...extra})});const o=await r.json();if(!r.ok||o.error){alert(o.error||"Request failed");return null}return o}
async function boot(){if(!db){root.innerHTML='<div class="panel empty">Supabase is not configured.</div>';return}user=(await db.auth.getUser()).data.user;if(!user){root.innerHTML='<div class="panel empty"><h2>Sign in to open Trust Center.</h2><a class="btn primary" href="account.html">Open account</a></div>';return}const c=await db.from("podcast_creators").select("podcast_id").eq("user_id",user.id).eq("can_manage",true).limit(1);podcastId=c.data?.[0]?.podcast_id;if(!podcastId){root.innerHTML='<div class="panel empty"><h2>No managed podcast found.</h2></div>';return}await refresh();db.channel("trust-center-5-13").on("postgres_changes",{event:"*",schema:"public",table:"podcast_live_moderator_roles"},refresh).on("postgres_changes",{event:"*",schema:"public",table:"podcast_live_audience_reports"},refresh).on("postgres_changes",{event:"*",schema:"public",table:"podcast_live_moderation_strikes"},refresh).on("postgres_changes",{event:"*",schema:"public",table:"podcast_live_automation_rules"},refresh).subscribe()}
async function refresh(){const [r,i,s,rep,st,ru,t,a]=await Promise.all([
db.from("podcast_live_moderator_roles").select("*").eq("podcast_id",podcastId).order("created_at"),
db.from("podcast_live_moderator_invitations").select("*").eq("podcast_id",podcastId).order("created_at",{ascending:false}).limit(30),
db.from("podcast_live_moderator_schedules").select("*").eq("podcast_id",podcastId).order("day_of_week"),
db.from("podcast_live_audience_reports").select("*").order("created_at",{ascending:false}).limit(50),
db.from("podcast_live_moderation_strikes").select("*").eq("podcast_id",podcastId).order("created_at",{ascending:false}).limit(100),
db.from("podcast_live_automation_rules").select("*").eq("podcast_id",podcastId).order("created_at",{ascending:false}),
db.from("podcast_live_trust_profiles").select("*").eq("podcast_id",podcastId).order("updated_at",{ascending:false}).limit(100),
db.from("podcast_live_moderation_actions").select("action,created_at,target_user_id").eq("broadcast_id","00000000-0000-0000-0000-000000000000").limit(1)
]);roles=r.data||[];invites=i.data||[];schedules=s.data||[];reports=rep.data||[];strikes=st.data||[];rules=ru.data||[];trust=t.data||[];actions=a.data||[];render()}
function render(){const open=reports.filter(x=>x.status==="open").length,review=reports.filter(x=>x.status==="reviewing").length,sev3=strikes.filter(x=>x.severity===3).length;const roleHtml=roles.map(x=>'<div class="item"><b>'+esc(x.role.replace("_"," "))+'</b><div class="small">'+esc(x.user_id)+'</div><div>'+["can_chat_moderate","can_timeout","can_control_reactions","can_send_alerts","can_manage_safety"].map(k=>'<span class="tag">'+k.replace("can_","")+(x[k]?" ✓":"")+'</span>').join("")+'</div><div class="toolbar"><button class="btn" data-edit="'+x.user_id+'">Edit permissions</button><button class="btn" data-remove="'+x.user_id+'">Deactivate</button></div></div>').join("");
const invHtml=invites.map(x=>'<div class="item"><b>'+esc(x.invited_email||x.invited_user_id||"Invitation")+'</b><div class="small">'+esc(x.role)+' • '+esc(x.status)+' • '+esc(ago(x.created_at))+'</div></div>').join("");
const repHtml=reports.slice(0,25).map(x=>'<div class="item"><b>'+esc(x.category)+'</b><div>'+esc(x.description||"No description")+'</div><div class="small">'+esc(x.status)+' • '+(x.assigned_to?esc(x.assigned_to):"Unassigned")+'</div><div class="toolbar">'+(x.status==="open"?'<button class="btn" data-assign="'+x.id+'">Assign</button>':"")+'<button class="btn" data-resolve="'+x.id+'">Resolve</button></div></div>').join("");
const strikeHtml=strikes.slice(0,30).map(x=>'<div class="item"><b>Severity '+x.severity+'</b><div>'+esc(x.reason||"Moderation strike")+'</div><div class="small">'+esc(x.user_id)+' • '+esc(ago(x.created_at))+'</div></div>').join("");
const ruleHtml=rules.map(x=>'<div class="item"><b>'+esc(x.name)+'</b><div class="small">'+esc(x.rule_type)+' → '+esc(x.action)+' • '+(x.enabled?"ENABLED":"DISABLED")+'</div><div class="toolbar"><button class="btn" data-rule="'+x.id+'">'+(x.enabled?"Disable":"Enable")+'</button></div></div>').join("");
const trustHtml=trust.map(x=>'<div class="item"><b>'+esc(x.trust_level.toUpperCase())+'</b><div class="small">'+esc(x.user_id)+(x.manual_override?" • manual override":"")+'</div><div class="toolbar"><button class="btn" data-trust="'+x.user_id+'">Change level</button></div></div>').join("");
const schedHtml=schedules.map(x=>'<div class="item"><b>'+["Sun","Mon","Tue","Wed","Thu","Fri","Sat"][x.day_of_week]+'</b><div>'+esc(x.start_time)+'–'+esc(x.end_time)+' • '+esc(x.timezone)+'</div><div class="small">'+esc(x.moderator_user_id)+'</div></div>').join("");
root.innerHTML='<section class="kpis"><div class="panel kpi"><span class="muted">Moderators</span><strong>'+fmt(roles.filter(x=>x.active).length)+'</strong></div><div class="panel kpi"><span class="muted">Pending invites</span><strong>'+fmt(invites.filter(x=>x.status==="pending").length)+'</strong></div><div class="panel kpi"><span class="muted">Open reports</span><strong>'+fmt(open)+'</strong></div><div class="panel kpi"><span class="muted">Reviewing</span><strong>'+fmt(review)+'</strong></div><div class="panel kpi"><span class="muted">Strikes</span><strong>'+fmt(strikes.length)+'</strong></div><div class="panel kpi"><span class="muted">Severe strikes</span><strong>'+fmt(sev3)+'</strong></div></section><section class="grid"><article class="panel card"><p class="eyebrow">MODERATOR ACCESS</p><h2>Team & Permissions</h2><div class="list">'+(roleHtml||'<div class="muted">No moderators.</div>')+'</div><div class="toolbar"><button class="btn primary" data-invite>Invite Moderator</button></div></article><article class="panel card"><p class="eyebrow">INVITATIONS</p><h2>Access Requests</h2><div class="list">'+(invHtml||'<div class="muted">No invitations.</div>')+'</div></article><article class="panel card"><p class="eyebrow">COVERAGE</p><h2>Moderator Schedules</h2><div class="list">'+(schedHtml||'<div class="muted">No schedules.</div>')+'</div><div class="toolbar"><button class="btn" data-schedule>Add Schedule</button></div></article><article class="panel card"><p class="eyebrow">ESCALATION</p><h2>Report Queue</h2><div class="list">'+(repHtml||'<div class="muted">No reports.</div>')+'</div></article><article class="panel card"><p class="eyebrow">STRIKE HISTORY</p><h2>Escalation Record</h2><div class="list">'+(strikeHtml||'<div class="muted">No strikes.</div>')+'</div></article><article class="panel card"><p class="eyebrow">AUTOMATION</p><h2>Moderation Rules</h2><div class="list">'+(ruleHtml||'<div class="muted">No rules configured.</div>')+'</div><div class="toolbar"><button class="btn primary" data-rule-add>Add Rule</button></div><p class="small muted">Rules are stored as explicit, auditable controls. They do not run automatically until an automation worker is connected.</p></article><article class="panel card"><p class="eyebrow">TRUST LEVELS</p><h2>Audience Trust</h2><div class="list">'+(trustHtml||'<div class="muted">No manual trust profiles.</div>')+'</div><p class="small muted">Levels are transparent creator controls: New, Standard, Trusted, Restricted.</p></article><article class="panel card"><p class="eyebrow">CREATOR SAFETY</p><h2>Operational Controls</h2><p>Use the Live Command Center for persistent chat/reaction state, alerts, audience controls and realtime moderation.</p><div class="toolbar"><a class="btn primary" href="live-command.html">Open Live Command Center</a><a class="btn" href="live-room.html">Open Live Room</a></div></article></section>'}
document.addEventListener("click",async e=>{const t=e.target;if(t.matches("[data-invite]")){const email=prompt("Moderator email:");if(email){const role=prompt("Role: moderator, senior_moderator, producer","moderator");if(role)await api("invite",{invited_email:email,role})}}else if(t.matches("[data-edit]")){const uid=t.dataset.edit;const r=roles.find(x=>x.user_id===uid);if(!r)return;const role=prompt("Role",r.role)||r.role;const p={};for(const k of ["can_chat_moderate","can_timeout","can_control_reactions","can_send_alerts","can_manage_safety"]){const v=prompt(k+" (true/false)",String(r[k]));if(v!==null)p[k]=v==="true"}await api("edit_role",{target_user_id:uid,role,permissions:p})}else if(t.matches("[data-remove]")){if(confirm("Deactivate this moderator?"))await api("remove_role",{target_user_id:t.dataset.remove})}else if(t.matches("[data-assign]")){const uid=prompt("Assign report to user ID:",user.id);if(uid)await api("assign_report",{report_id:t.dataset.assign,target_user_id:uid})}else if(t.matches("[data-resolve]")){const q=await db.from("podcast_live_audience_reports").update({status:"resolved",reviewed_by:user.id,reviewed_at:new Date().toISOString()}).eq("id",t.dataset.resolve);if(q.error)alert(q.error.message)}else if(t.matches("[data-rule-add]")){const name=prompt("Rule name:","Spam keyword rule");if(name){const type=prompt("Type: keyword, rate_limit, report_threshold, repeat_offense","keyword");const action=prompt("Action: warn, timeout, ban, hide_message, disable_reactions, alert","warn");const q=await db.from("podcast_live_automation_rules").insert({podcast_id:podcastId,name,rule_type:type,action,created_by:user.id,keywords:type==="keyword"?(prompt("Comma-separated keywords:","")||"").split(",").map(x=>x.trim()).filter(Boolean):[],threshold:Number(prompt("Threshold (optional):","3"))||null});if(q.error)alert(q.error.message)}}else if(t.matches("[data-rule]")){const r=rules.find(x=>String(x.id)===t.dataset.rule);if(r){const q=await db.from("podcast_live_automation_rules").update({enabled:!r.enabled,updated_at:new Date().toISOString()}).eq("id",r.id);if(q.error)alert(q.error.message)}}else if(t.matches("[data-trust]")){const level=prompt("Trust level: new, standard, trusted, restricted","standard");if(level)await api("trust",{target_user_id:t.dataset.trust,trust_level:level})}else if(t.matches("[data-schedule]")){const uid=prompt("Moderator user ID:");if(uid){const day=Number(prompt("Day 0=Sun through 6=Sat","1"));const start=prompt("Start time HH:MM","09:00");const end=prompt("End time HH:MM","17:00");const tz=prompt("Timezone","America/Los_Angeles");const q=await db.from("podcast_live_moderator_schedules").insert({podcast_id:podcastId,moderator_user_id:uid,day_of_week:day,start_time:start,end_time:end,timezone:tz,created_by:user.id});if(q.error)alert(q.error.message)}}refresh()});
boot().catch(e=>{console.error(e);root.innerHTML='<div class="panel empty"><h2>Trust Center error</h2><p>'+esc(e.message||e)+'</p></div>'});