import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import Stripe from "npm:stripe@22.6.2";
import {createClient} from "jsr:@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,x-client-info,apikey,content-type","Access-Control-Allow-Methods":"POST,OPTIONS","Content-Type":"application/json"};
const json=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:cors});
const db=()=>createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false}});
const st=()=>new Stripe(Deno.env.get("STRIPE_SECRET_KEY")!,{apiVersion:"2026-08-26.dahlia"});
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{
 const h=req.headers.get("Authorization");if(!h)return json({error:"Authentication required."},401);
 const u=(await db().auth.getUser(h.replace(/^Bearer\s+/i,""))).data.user;if(!u)return json({error:"Authentication required."},401);
 const b=await req.json(),productId=String(b.product_id||""),podcastId=String(b.podcast_id||"");if(!productId||!podcastId)return json({error:"product_id and podcast_id are required."},400);
 const d=db(),q=await d.from("cr_podcast_monetization_products").select("id,creator_id,podcast_id,name,description,currency,amount_cents,interval,interval_count,trial_period_days,stripe_price_id,active").eq("id",productId).eq("podcast_id",podcastId).eq("product_type","membership").eq("active",true).maybeSingle();if(q.error)throw q.error;if(!q.data?.stripe_price_id)return json({error:"This subscription plan is no longer available."},404);
 const p=q.data,sa=(await d.from("cr_podcast_stripe_accounts").select("stripe_account_id,charges_enabled,payouts_enabled").eq("creator_id",p.creator_id).maybeSingle()).data;if(!sa?.stripe_account_id||!sa.charges_enabled||!sa.payouts_enabled)return json({error:"This creator has not completed Stripe onboarding."},409);
 const account=await st().v2.core.accounts.retrieve(sa.stripe_account_id),ts=account?.configuration?.recipient?.capabilities?.stripe_balance?.stripe_transfers?.status;if(ts!=="active")return json({error:"This creator cannot currently receive subscription transfers."},409);
 const ex=await d.from("podcast_subscriptions").select("id").eq("user_id",u.id).eq("podcast_id",podcastId).in("status",["trialing","active","past_due","paused"]).limit(1);if(ex.data?.length)return json({error:"You already have an active subscription to this podcast."},409);
 const base=String(b.origin||"https://crowrulesentertainment-oss.github.io/podcasting/").replace(/\/$/,""),s=await st().checkout.sessions.create({mode:"subscription",success_url:base+"/podcast.html?id="+encodeURIComponent(podcastId)+"&subscription=success&session_id={CHECKOUT_SESSION_ID}",cancel_url:base+"/podcast.html?id="+encodeURIComponent(podcastId)+"&subscription=cancelled",customer_email:u.email||undefined,client_reference_id:u.id,line_items:[{price:p.stripe_price_id,quantity:1}],billing_address_collection:"auto",payment_method_collection:"always",automatic_tax:{enabled:false},allow_promotion_codes:false,integration_identifier:"crowrules_podcasting_subscription_0001",subscription_data:{...(Number(p.trial_period_days)>0?{trial_period_days:Number(p.trial_period_days)}:{}),application_fee_percent:20,transfer_data:{destination:sa.stripe_account_id},metadata:{crowrules_flow:"podcast_subscription",crowrules_user_id:u.id,crowrules_creator_id:p.creator_id,crowrules_podcast_id:podcastId,crowrules_product_id:p.id,crowrules_price_id:p.stripe_price_id,platform_fee_percent:"20"}},metadata:{crowrules_flow:"podcast_subscription",crowrules_user_id:u.id,crowrules_creator_id:p.creator_id,crowrules_podcast_id:podcastId,crowrules_product_id:p.id,crowrules_price_id:p.stripe_price_id,platform_fee_percent:"20"}});
 return json({ok:true,url:s.url,session_id:s.id});
}catch(e:any){console.error("podcast-subscription-checkout",e);return json({error:e?.message||"Unable to create subscription checkout."},Number(e?.status)||500)}});