import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import Stripe from "npm:stripe@22.6.2";
import {createClient} from "jsr:@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type,stripe-signature","Access-Control-Allow-Methods":"POST,OPTIONS","Content-Type":"application/json"};
const json=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:cors});const db=()=>createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false}});const stripe=()=>new Stripe(Deno.env.get("STRIPE_SECRET_KEY")!,{apiVersion:"2026-08-26.dahlia"});const iso=(v:any)=>v?new Date(Number(v)*1000).toISOString():null;
async function sync(st:Stripe,id:string,sessionId?:string,eventId?:string,eventType?:string){
 const sub:any=await st.subscriptions.retrieve(id),m=sub.metadata||{},d=db(),uid=String(m.crowrules_user_id||""),pid=String(m.crowrules_podcast_id||""),prod=String(m.crowrules_product_id||"");
 if(!uid||!pid||!prod)return;
 const p=(await d.from("cr_podcast_monetization_products").select("id,creator_id,podcast_id,amount_cents,currency,stripe_price_id").eq("id",prod).maybeSingle()).data;if(!p)return;
 const customer=typeof sub.customer==="string"?sub.customer:sub.customer?.id||null;
 const existing=(await d.from("podcast_subscriptions").select("id,product_id,amount_cents,status,cancel_at_period_end,canceled_at,creator_id,podcast_id,user_id").eq("stripe_subscription_id",sub.id).maybeSingle()).data;
 const nextStatus=String(sub.status||"incomplete"),nextCancel=Boolean(sub.cancel_at_period_end),nextCanceled=iso(sub.canceled_at);
 const row={user_id:uid,creator_id:p.creator_id,podcast_id:pid,product_id:p.id,stripe_customer_id:customer,stripe_subscription_id:sub.id,stripe_checkout_session_id:sessionId||undefined,stripe_price_id:p.stripe_price_id,amount_cents:p.amount_cents,currency:p.currency||"usd",status:nextStatus,started_at:iso(sub.start_date)||existing?.started_at||new Date().toISOString(),current_period_start:iso(sub.current_period_start),current_period_end:iso(sub.current_period_end),cancel_at_period_end:nextCancel,canceled_at:nextCanceled,updated_at:new Date().toISOString()};
 const r=await d.from("podcast_subscriptions").upsert(row,{onConflict:"stripe_subscription_id"});if(r.error)throw r.error;
 const eventBase={subscription_id:existing?.id||null,stripe_subscription_id:String(sub.id),user_id:uid,creator_id:p.creator_id,podcast_id:pid,from_product_id:existing?.product_id||null,to_product_id:p.id,from_status:existing?.status||null,to_status:nextStatus,from_amount_cents:existing?.amount_cents??null,to_amount_cents:p.amount_cents,currency:p.currency||"usd",stripe_event_id:eventId||null,occurred_at:new Date().toISOString(),metadata:{stripe_event_type:eventType||null,session_id:sessionId||null}};
 let type:string|null=null;
 if(!existing)type="started";
 else if(existing.product_id!==p.id){
   type=(Number(p.amount_cents||0)>Number(existing.amount_cents||0))?"plan_upgrade":(Number(p.amount_cents||0)<Number(existing.amount_cents||0)?"plan_downgrade":"plan_change");
 }else if(existing.cancel_at_period_end&&!nextCancel&&!nextCanceled)type="reactivated";
 else if(!existing.cancel_at_period_end&&nextCancel)type="cancellation_scheduled";
 else if(existing.status!==nextStatus)type=nextStatus==="canceled"?"canceled":"status_change";
 if(type){
   const er=await d.from("podcast_subscription_events").insert({...eventBase,event_type:type});if(er.error&&er.code!=="23505")throw er.error;
 }
}

async function revenue(st:Stripe,inv:any){const sid=typeof inv.subscription==="string"?inv.subscription:inv.subscription?.id;if(!sid)return;const sub:any=await st.subscriptions.retrieve(sid),m=sub.metadata||{},cid=String(m.crowrules_creator_id||""),uid=String(m.crowrules_user_id||""),pid=String(m.crowrules_podcast_id||"");if(!cid||!uid||!pid)return;const amount=Number(inv.amount_paid||0);if(amount<=0)return;const fee=Math.floor(amount*Number(m.platform_fee_percent||20)/100),net=amount-fee,pi=typeof inv.payment_intent==="string"?inv.payment_intent:inv.payment_intent?.id||null,now=new Date().toISOString();let charge:any=null;try{if(pi){const p:any=await st.paymentIntents.retrieve(pi),ch=typeof p.latest_charge==="string"?p.latest_charge:p.latest_charge?.id;if(ch)charge=await st.charges.retrieve(ch)}}catch(e){console.warn("charge lookup",e)}const tx={user_id:uid,creator_id:cid,podcast_id:pid,stripe_transaction_id:pi||String(inv.id),transaction_type:"subscription_payment",stripe_customer_id:typeof inv.customer==="string"?inv.customer:null,stripe_payment_id:pi,stripe_invoice_id:String(inv.id),gross_amount:amount,platform_fee:fee,creator_amount:net,currency:String(inv.currency||"usd"),status:"available",description:"Podcast subscription payment",metadata:m,occurred_at:now,stripe_fee:0,event_type:"invoice.paid",stripe_charge_id:charge?.id||null,stripe_payment_intent_id:pi,transfer_id:typeof charge?.transfer==="string"?charge.transfer:charge?.transfer?.id||null,reconciliation_status:"reconciled",reconciled_at:now,refunded_amount:0,transfer_reversed_amount:0,refunded_platform_fee:0};const r=await db().from("cr_creator_revenue_transactions").upsert(tx,{onConflict:"stripe_transaction_id"});if(r.error)throw r.error;const e={creator_id:cid,podcast_id:pid,source_type:"podcast_subscription",source_id:pi||String(inv.id),gross_amount_cents:amount,platform_fee_cents:fee,net_amount_cents:net,currency:String(inv.currency||"usd"),status:"available",description:"Podcast subscription payment",occurred_at:now,updated_at:now,stripe_payment_intent_id:pi,stripe_charge_id:charge?.id||null,refunded_amount_cents:0,reconciliation_status:"reconciled",reconciled_at:now,refunded_platform_fee_cents:0};const er=await db().from("cr_podcast_creator_earnings").upsert(e,{onConflict:"source_id"});if(er.error)throw er.error}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({error:"POST required."},405);const secret=Deno.env.get("STRIPE_WEBHOOK_SECRET"),key=Deno.env.get("STRIPE_SECRET_KEY");if(!secret||!key)return json({error:"Stripe webhook secrets are not configured."},503);try{const raw=await req.text(),sig=req.headers.get("stripe-signature");if(!sig)return json({error:"Missing Stripe signature."},400);const st=stripe(),ev:any=await st.webhooks.constructEventAsync(raw,sig,secret,undefined,Stripe.createSubtleCryptoProvider()),d=db(),seen=(await d.from("cr_podcast_stripe_webhook_events").select("status").eq("stripe_event_id",ev.id).maybeSingle()).data;if(seen?.status==="processed")return json({received:true,duplicate:true});const o:any=ev.data.object;if(ev.type==="checkout.session.completed"&&o.mode==="subscription"&&o.subscription)await sync(st,String(o.subscription),o.id,ev.id,ev.type);else if(ev.type==="customer.subscription.created"||ev.type==="customer.subscription.updated")await sync(st,String(o.id),undefined,ev.id,ev.type);else if(ev.type==="customer.subscription.deleted"){const prev=(await d.from("podcast_subscriptions").select("id,user_id,creator_id,podcast_id,product_id,amount_cents,status").eq("stripe_subscription_id",String(o.id)).maybeSingle()).data;const ur=await d.from("podcast_subscriptions").update({status:"canceled",cancel_at_period_end:false,canceled_at:iso(o.canceled_at)||new Date().toISOString(),updated_at:new Date().toISOString()}).eq("stripe_subscription_id",String(o.id));if(ur.error)throw ur.error;if(prev){const er=await d.from("podcast_subscription_events").insert({subscription_id:prev.id,stripe_subscription_id:String(o.id),user_id:prev.user_id,creator_id:prev.creator_id,podcast_id:prev.podcast_id,from_product_id:prev.product_id,to_product_id:prev.product_id,event_type:"canceled",from_status:prev.status,to_status:"canceled",from_amount_cents:prev.amount_cents,to_amount_cents:prev.amount_cents,currency:"usd",stripe_event_id:ev.id,occurred_at:new Date().toISOString(),metadata:{stripe_event_type:ev.type}});if(er.error&&er.code!=="23505")throw er.error;}}else if(ev.type==="invoice.paid"){await revenue(st,o);if(o.subscription)await sync(st,typeof o.subscription==="string"?o.subscription:o.subscription.id,undefined,ev.id,ev.type)}else if(ev.type==="invoice.payment_failed"&&o.subscription)await sync(st,typeof o.subscription==="string"?o.subscription:o.subscription.id);const r=await d.from("cr_podcast_stripe_webhook_events").upsert({stripe_event_id:ev.id,event_type:ev.type,status:"processed",received_at:new Date().toISOString(),processed_at:new Date().toISOString()},{onConflict:"stripe_event_id"});if(r.error)throw r.error;return json({received:true,event_type:ev.type})}catch(e:any){console.error("creator-payment-webhook",e);return json({error:e?.message||"Webhook processing failed."},400)}});