import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import Stripe from "npm:stripe@22.6.2";
import {createClient} from "jsr:@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,x-client-info,apikey,content-type","Access-Control-Allow-Methods":"POST,OPTIONS","Content-Type":"application/json"};
const db=()=>createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false}});
const stripe=()=>new Stripe(Deno.env.get("STRIPE_SECRET_KEY")!,{apiVersion:"2026-03-25.dahlia; custom_checkout_payment_form_preview=v1"});
const out=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:cors});
async function user(req:Request){const h=req.headers.get("Authorization");if(!h)throw Object.assign(Error("Authentication required."),{status:401});const r=await db().auth.getUser(h.replace(/^Bearer\s+/i,""));if(r.error||!r.data.user)throw Object.assign(Error("Authentication required."),{status:401});return r.data.user}
async function creator(uid:string){const d=db();const m=await d.from("members").select("id").eq("user_id",uid).maybeSingle();if(m.error)throw m.error;if(!m.data)throw Object.assign(Error("No CrowRules member profile is linked to this account."),{status:403});const c=await d.from("creators").select("id,name,display_name,is_active").eq("member_id",m.data.id).maybeSingle();if(c.error)throw c.error;if(!c.data||c.data.is_active===false)throw Object.assign(Error("No active creator profile is linked to this account."),{status:403});const s=await d.from("cr_podcast_stripe_accounts").select("stripe_account_id,onboarding_status,charges_enabled,payouts_enabled").eq("creator_id",c.data.id).maybeSingle();if(s.error)throw s.error;return {...c.data,stripe:s.data}}
function validate(b:any){const name=String(b.name||"").trim(),description=String(b.description||"").trim(),amount=Math.round(Number(b.amount_cents)),interval=String(b.interval||"month"),interval_count=Number(b.interval_count||1),trial_period_days=Number(b.trial_period_days||0);if(!name||name.length>120)throw Error("Plan name is required and must be 120 characters or fewer.");if(description.length>2000)throw Error("Description is too long.");if(!Number.isInteger(amount)||amount<50||amount>99999999)throw Error("Price must be between $0.50 and $999,999.99.");if(!["month","year"].includes(interval))throw Error("Billing must be monthly or yearly.");if(!Number.isInteger(interval_count)||interval_count<1||interval_count>36)throw Error("Billing interval count must be 1–36.");if(!Number.isInteger(trial_period_days)||trial_period_days<0||trial_period_days>365)throw Error("Trial must be 0–365 days.");return{name,description,amount,interval,interval_count,trial_period_days}}
async function list(c:any){const d=db();const [p,shows]=await Promise.all([d.from("cr_podcast_monetization_products").select("id,podcast_id,name,description,currency,stripe_product_id,stripe_price_id,amount_cents,interval,interval_count,trial_period_days,active,display_order,features,grants_premium_access,created_at,updated_at").eq("creator_id",c.id).eq("product_type","membership").order("display_order").order("created_at",{ascending:false}),d.from("podcasts").select("id,title,slug,status,artwork_url").eq("creator_id",c.id).order("created_at",{ascending:false})]);if(p.error)throw p.error;if(shows.error)throw shows.error;return{ok:true,creator:{id:c.id,name:c.display_name||c.name,stripe_ready:!!(c.stripe?.charges_enabled&&c.stripe?.payouts_enabled),onboarding_status:c.stripe?.onboarding_status||"not_connected"},podcasts:shows.data||[],plans:p.data||[]}}
async function create(c:any,b:any){if(!c.stripe?.stripe_account_id||!c.stripe.charges_enabled||!c.stripe.payouts_enabled)throw Error("Stripe onboarding must be complete before creating paid plans.");const p=validate(b),pod=b.podcast_id?String(b.podcast_id):null,d=db();if(pod){const q=await d.from("podcasts").select("id").eq("id",pod).eq("creator_id",c.id).maybeSingle();if(q.error)throw q.error;if(!q.data)throw Error("Selected podcast does not belong to this creator.")}const product=await stripe().products.create({name:p.name,description:p.description||undefined,active:true,metadata:{crowrules_product_type:"membership",crowrules_creator_id:c.id,...(pod?{crowrules_podcast_id:pod}:{})}});try{const price=await stripe().prices.create({product:product.id,currency:"usd",unit_amount:p.amount,recurring:{interval:p.interval as any,interval_count:p.interval_count},metadata:{crowrules_product_type:"membership",crowrules_creator_id:c.id}});const row=await d.from("cr_podcast_monetization_products").insert({creator_id:c.id,podcast_id:pod,product_type:"membership",name:p.name,description:p.description||null,currency:"usd",stripe_product_id:product.id,stripe_price_id:price.id,amount_cents:p.amount,interval:p.interval,interval_count:p.interval_count,trial_period_days:p.trial_period_days,active:true,grants_premium_access:true,features:[]}).select("*").single();if(row.error)throw row.error;return row.data}catch(e){await stripe().products.update(product.id,{active:false}).catch(()=>{});throw e}}
async function update(c:any,b:any){const d=db(),q=await d.from("cr_podcast_monetization_products").select("*").eq("id",b.id).eq("creator_id",c.id).eq("product_type","membership").maybeSingle();if(q.error)throw q.error;if(!q.data)throw Error("Subscription plan not found.");const old=q.data,p=validate(b);if(old.stripe_product_id)await stripe().products.update(old.stripe_product_id,{name:p.name,description:p.description||undefined,active:b.active!==false});let price=old.stripe_price_id;if(Number(old.amount_cents)!==p.amount||old.interval!==p.interval||Number(old.interval_count||1)!==p.interval_count){const np=await stripe().prices.create({product:old.stripe_product_id,currency:"usd",unit_amount:p.amount,recurring:{interval:p.interval as any,interval_count:p.interval_count},metadata:{crowrules_product_type:"membership",crowrules_creator_id:c.id,crowrules_replaced_price_id:old.stripe_price_id||""}});if(old.stripe_price_id)await stripe().prices.update(old.stripe_price_id,{active:false}).catch(()=>{});price=np.id}const r=await d.from("cr_podcast_monetization_products").update({name:p.name,description:p.description||null,amount_cents:p.amount,interval:p.interval,interval_count:p.interval_count,trial_period_days:p.trial_period_days,active:b.active!==false,stripe_price_id:price,updated_at:new Date().toISOString()}).eq("id",old.id).eq("creator_id",c.id).select("*").single();if(r.error)throw r.error;return r.data}
async function deactivate(c:any,b:any){const d=db(),q=await d.from("cr_podcast_monetization_products").select("id,stripe_product_id,stripe_price_id").eq("id",b.id).eq("creator_id",c.id).eq("product_type","membership").maybeSingle();if(q.error)throw q.error;if(!q.data)throw Error("Subscription plan not found.");if(q.data.stripe_price_id)await stripe().prices.update(q.data.stripe_price_id,{active:false});if(q.data.stripe_product_id)await stripe().products.update(q.data.stripe_product_id,{active:false});const r=await d.from("cr_podcast_monetization_products").update({active:false,updated_at:new Date().toISOString()}).eq("id",q.data.id).select("*").single();if(r.error)throw r.error;return r.data}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{const u=await user(req),c=await creator(u.id),b=await req.json().catch(()=>({})),a=String(b.action||"list");if(a==="list")return out(await list(c));if(a==="create")return out({ok:true,plan:await create(c,b)});if(a==="update")return out({ok:true,plan:await update(c,b)});if(a==="deactivate")return out({ok:true,plan:await deactivate(c,b)});if(a==="health")return out({ok:true,service:"creator-subscription-manager"});return out({error:"Unknown action."},400)}catch(e:any){console.error("creator-subscription-manager",e?.message||e);return out({error:e?.message||"Creator subscription service error."},Number(e?.status)||500)}});
