const SUPABASE_URL="https://cevylpnoexugwgygvtgu.supabase.co";
const SUPABASE_KEY="sb_publishable_AdfM5y6RqvF3tbvEVzDZSg_JuGTQLD-";
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=s=>document.querySelector(s);
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const fmt=v=>v?new Date(v).toLocaleString():"—";
function notice(message,type="ok"){const e=$("#notice");e.innerHTML='<div class="notice '+(type==="bad"?"error":"success")+'">'+esc(message)+"</div>";setTimeout(()=>e.innerHTML="",4500)}
async function adminCheck(){const {data:{session}}=await sb.auth.getSession();if(!session){showGate("You are not signed in.");return false}
const {data,error}=await sb.rpc("crowrules_is_admin");if(error||data!==true){showGate("Your account is signed in, but it does not have CrowRules administrator access.");return false}
$("#adminApp").classList.remove("hidden");$("#adminStatus").textContent="ADMIN VERIFIED";$("#adminStatus").classList.add("ok");return true}
function showGate(msg){$("#loginGate").classList.remove("hidden");$("#gateMessage").textContent=msg}
async function rows(table,select="*"){const {data,error}=await sb.from(table).select(select);if(error)throw error;return data||[]}
async function remove(table,id){if(!confirm("Delete this record? This cannot be undone."))return;const {error}=await sb.from(table).delete().eq("id",id);if(error)throw error;notice("Record deleted.");await refreshAll()}
async function update(table,id,patch){const {error}=await sb.from(table).update(patch).eq("id",id);if(error)throw error;notice("Record updated.");await refreshAll()}
async function refreshStats(){const tables=["podcasts","cr_podcast_episodes","podcast_news","cr_podcast_schedule","cr_podcast_live","podcast_live_channels"];const counts=await Promise.all(tables.map(async t=>{try{return [t,(await sb.from(t).select("id",{count:"exact",head:true})).count||0]}catch{return[t,0]}}));const names={podcasts:"Podcasts",cr_podcast_episodes:"Episodes",podcast_news:"News Articles",cr_podcast_schedule:"Schedule Items",cr_podcast_live:"Live Records",podcast_live_channels:"Live Channels"};$("#stats").innerHTML=counts.map(([k,v])=>'<div class="statbox"><b>'+v+'</b><span>'+names[k]+"</span></div>").join("")}
async function loadPodcasts(){const data=await rows("podcasts","id,title,slug,category,status,is_featured,total_plays,created_at");$("#podcastRows").innerHTML=data.length?data.map(x=>'<tr><td><strong>'+esc(x.title)+'</strong><div class="small">'+esc(x.slug)+'</div></td><td>'+esc(x.status)+'</td><td>'+esc(x.category)+'</td><td>'+Number(x.total_plays||0).toLocaleString()+'</td><td><button class="btn ghost" data-action="publish-podcast" data-id="'+x.id+'">'+(x.status==="published"?"Archive":"Publish")+'</button> <button class="btn danger" data-action="delete-podcast" data-id="'+x.id+'">Delete</button></td></tr>').join(""):'<tr><td colspan="5"><div class="empty">No podcasts.</div></td></tr>';populatePodcastSelects(data)}
function populatePodcastSelects(data){for(const id of ["episodePodcast","schedulePodcast"]){const e=$("#"+id);if(!e)continue;const old=e.value;e.innerHTML='<option value="">Select podcast</option>'+data.map(x=>'<option value="'+x.id+'">'+esc(x.title)+'</option>').join("");e.value=old}}
async function loadEpisodes(){const eps=await rows("cr_podcast_episodes","id,podcast_id,title,slug,is_published,is_featured,listen_count,created_at");const pods=await rows("podcasts","id,title");const map=Object.fromEntries(pods.map(p=>[p.id,p.title]));$("#episodeRows").innerHTML=eps.length?eps.map(x=>'<tr><td><strong>'+esc(x.title)+'</strong><div class="small">'+esc(x.slug||"")+'</div></td><td>'+esc(map[x.podcast_id]||"Unassigned")+'</td><td>'+((x.is_published)?'<span class="badge">Published</span>':'Draft')+'</td><td>'+Number(x.listen_count||0).toLocaleString()+'</td><td><button class="btn ghost" data-action="toggle-episode" data-id="'+x.id+'" data-value="'+(!x.is_published)+'">'+(x.is_published?"Unpublish":"Publish")+'</button> <button class="btn danger" data-action="delete-episode" data-id="'+x.id+'">Delete</button></td></tr>').join(""):'<tr><td colspan="5"><div class="empty">No episodes.</div></td></tr>';populateEpisodeSelect(eps)}
function populateEpisodeSelect(eps){const e=$("#scheduleEpisode");const old=e.value;e.innerHTML='<option value="">None</option>'+eps.map(x=>'<option value="'+x.id+'">'+esc(x.title)+'</option>').join("");e.value=old}
async function loadLive(){const data=await rows("cr_podcast_live","id,title,show_name,is_live,listener_count,updated_at");$("#liveRows").innerHTML=data.length?data.map(x=>'<tr><td><strong>'+esc(x.title)+'</strong><div class="small">'+esc(x.show_name||"")+'</div></td><td>'+(x.is_live?'<span class="badge">LIVE</span>':'Offline')+'</td><td>'+Number(x.listener_count||0).toLocaleString()+'</td><td>'+fmt(x.updated_at)+'</td><td><button class="btn ghost" data-action="toggle-live" data-id="'+x.id+'" data-value="'+(!x.is_live)+'">'+(x.is_live?"End":"Go Live")+'</button> <button class="btn danger" data-action="delete-live" data-id="'+x.id+'">Delete</button></td></tr>').join(""):'<tr><td colspan="5"><div class="empty">No live records.</div></td></tr>'}
async function loadSchedule(){const data=await rows("cr_podcast_schedule","id,title,starts_at,status,is_featured");$("#scheduleRows").innerHTML=data.length?data.sort((a,b)=>new Date(a.starts_at)-new Date(b.starts_at)).map(x=>'<tr><td>'+esc(x.title)+'</td><td>'+fmt(x.starts_at)+'</td><td>'+esc(x.status)+'</td><td>'+((x.is_featured)?"Yes":"No")+'</td><td><button class="btn danger" data-action="delete-schedule" data-id="'+x.id+'">Delete</button></td></tr>').join(""):'<tr><td colspan="5"><div class="empty">No schedule items.</div></td></tr>'}
async function loadNews(){const data=await rows("podcast_news","id,title,slug,category,status,published_at,created_at");$("#newsRows").innerHTML=data.length?data.sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)).map(x=>'<tr><td><strong>'+esc(x.title)+'</strong><div class="small">'+esc(x.slug)+'</div></td><td>'+esc(x.status)+'</td><td>'+esc(x.category||"")+'</td><td>'+fmt(x.published_at)+'</td><td><button class="btn ghost" data-action="toggle-news" data-id="'+x.id+'" data-status="'+(x.status==="published"?"draft":"published")+'">'+(x.status==="published"?"Unpublish":"Publish")+'</button> <button class="btn danger" data-action="delete-news" data-id="'+x.id+'">Delete</button></td></tr>').join(""):'<tr><td colspan="5"><div class="empty">No news articles.</div></td></tr>'}
async function loadTop(){const {data,error}=await sb.from("podcast_top10_podcasts_current").select("*").order("rank",{ascending:true}).limit(10);if(error)throw error;$("#top10Rows").innerHTML=(data||[]).map(x=>'<div class="card rank"><div class="ranknum">'+x.rank+'</div><div><h3>'+esc(x.title)+'</h3><p>'+esc(x.category||"")+" · "+Number(x.plays||0).toLocaleString()+" plays · "+Number(x.followers||0).toLocaleString()+" followers</p></div></div>").join("")||'<div class="empty">No ranking data yet.</div>'}
async function refreshAll(){try{await Promise.all([refreshStats(),loadPodcasts(),loadEpisodes(),loadLive(),loadSchedule(),loadNews(),loadTop()])}catch(e){console.error(e);notice(e.message||"Unable to load admin data.","bad")}}
function formObject(form){return Object.fromEntries(new FormData(form).entries())}
$("#logoutBtn").addEventListener("click",async e=>{e.preventDefault();await sb.auth.signOut();location.href="../index.html"});
document.querySelectorAll(".tab").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".tab-panel").forEach(x=>x.classList.add("hidden"));b.classList.add("active");$("#"+b.dataset.tab).classList.remove("hidden")}));
$("#podcastForm").addEventListener("submit",async e=>{e.preventDefault();try{const f=formObject(e.target);const {error}=await sb.from("podcasts").insert({title:f.title,slug:f.slug,category:f.category||"Talk & Commentary",creator_id:f.creator_id||null,description:f.description||null,artwork_url:f.artwork_url||null,trailer_url:f.trailer_url||null,website_url:f.website_url||null,rss_url:f.rss_url||null,status:f.status,is_featured:$("#podFeatured").checked});if(error)throw error;e.target.reset();notice("Podcast created.");await refreshAll()}catch(x){notice(x.message,"bad")}});
$("#episodeForm").addEventListener("submit",async e=>{e.preventDefault();try{const f=formObject(e.target);const {error}=await sb.from("cr_podcast_episodes").insert({podcast_id:f.podcast_id||null,title:f.title,slug:f.slug||null,category:f.category||null,episode_number:f.episode_number?Number(f.episode_number):null,season_number:f.season_number?Number(f.season_number):null,audio_url:f.audio_url||null,cover_url:f.cover_url||null,description:f.description||null,is_published:$("#epPublished").checked,is_featured:$("#epFeatured").checked,published_at:$("#epPublished").checked?new Date().toISOString():null});if(error)throw error;e.target.reset();notice("Episode created.");await refreshAll()}catch(x){notice(x.message,"bad")}});
$("#liveForm").addEventListener("submit",async e=>{e.preventDefault();try{const f=formObject(e.target);const patch={title:f.title,show_name:f.show_name||null,description:f.description||null,stream_url:f.stream_url||null,stream_type:f.stream_type||"audio",artwork_url:f.artwork_url||null,is_live:$("#liveNow").checked,started_at:$("#liveNow").checked?new Date().toISOString():null,ended_at:$("#liveNow").checked?null:new Date().toISOString()};const current=await rows("cr_podcast_live","id");let error;if(current[0])({error}=await sb.from("cr_podcast_live").update(patch).eq("id",current[0].id));else({error}=await sb.from("cr_podcast_live").insert(patch));if(error)throw error;notice("Live broadcast saved.");await refreshAll()}catch(x){notice(x.message,"bad")}});
$("#scheduleForm").addEventListener("submit",async e=>{e.preventDefault();try{const f=formObject(e.target);const {error}=await sb.from("cr_podcast_schedule").insert({title:f.title,podcast_id:f.podcast_id||null,episode_id:f.episode_id||null,starts_at:new Date(f.starts_at).toISOString(),ends_at:f.ends_at?new Date(f.ends_at).toISOString():null,status:f.status,description:f.description||null,is_featured:$("#schedFeatured").checked});if(error)throw error;e.target.reset();notice("Schedule item added.");await refreshAll()}catch(x){notice(x.message,"bad")}});
$("#newsForm").addEventListener("submit",async e=>{e.preventDefault();try{const f=formObject(e.target);const published=f.status==="published";const {error}=await sb.from("podcast_news").insert({title:f.title,slug:f.slug,category:f.category||null,image_url:f.image_url||null,excerpt:f.excerpt||null,body:f.body||null,status:f.status,published_at:published?new Date().toISOString():null});if(error)throw error;e.target.reset();notice("News article saved.");await refreshAll()}catch(x){notice(x.message,"bad")}});
document.addEventListener("click",async e=>{const b=e.target.closest("[data-action]");if(!b)return;try{const id=b.dataset.id;switch(b.dataset.action){case"delete-podcast":await remove("podcasts",id);break;case"publish-podcast":await update("podcasts",id,{status:b.textContent.trim()==="Publish"?"published":"archived"});break;case"delete-episode":await remove("cr_podcast_episodes",id);break;case"toggle-episode":await update("cr_podcast_episodes",id,{is_published:b.dataset.value==="true",published_at:b.dataset.value==="true"?new Date().toISOString():null});break;case"delete-live":await remove("cr_podcast_live",id);break;case"toggle-live":await update("cr_podcast_live",id,{is_live:b.dataset.value==="true",started_at:b.dataset.value==="true"?new Date().toISOString():null,ended_at:b.dataset.value==="true"?null:new Date().toISOString()});break;case"delete-schedule":await remove("cr_podcast_schedule",id);break;case"delete-news":await remove("podcast_news",id);break;case"toggle-news":await update("podcast_news",id,{status:b.dataset.status,published_at:b.dataset.status==="published"?new Date().toISOString():null});break}}catch(x){notice(x.message||"Action failed.","bad")}});
(async()=>{try{if(await adminCheck())await refreshAll()}catch(e){console.error(e);showGate("Admin verification failed. Please sign in again.")}})();