-- CrowRules Podcasting home live chat
-- Run in Supabase SQL Editor for project configured by config.js.
create table if not exists public.podcasting_chat_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  display_name text not null default 'CrowRules Member' check (char_length(display_name) between 1 and 80),
  message text not null check (char_length(trim(message)) between 1 and 1000),
  created_at timestamptz not null default now()
);

alter table public.podcasting_chat_messages enable row level security;

grant select on public.podcasting_chat_messages to anon, authenticated;
grant insert on public.podcasting_chat_messages to authenticated;
grant usage, select on sequence public.podcasting_chat_messages_id_seq to authenticated;

drop policy if exists "Anyone can read podcasting chat" on public.podcasting_chat_messages;
create policy "Anyone can read podcasting chat"
on public.podcasting_chat_messages for select
to anon, authenticated
using (true);

drop policy if exists "Signed-in members can post chat" on public.podcasting_chat_messages;
create policy "Signed-in members can post chat"
on public.podcasting_chat_messages for insert
to authenticated
with check (
  auth.uid() = user_id
  and char_length(trim(message)) between 1 and 1000
  and char_length(display_name) between 1 and 80
);

-- Enable INSERT events for Supabase Realtime. Safe to run more than once.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'podcasting_chat_messages'
  ) then
    alter publication supabase_realtime add table public.podcasting_chat_messages;
  end if;
end $$;
